// GENERATED by gen-armory.mjs — do not edit
/**
 * absolution — 5★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/Absolution.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { AbsolutionStatTable } from "../generated/weaponStatTables.js";

export const absolution: DbObjectWeapon = {
  name: "absolution",
  serializeId: 173,
  gameId: 11515,
  rarity: 5,
  weapon: "sword",
  statTable: AbsolutionStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_absolution",
      description: "talent_descr.weapon_absolution_1",
      refinementStats: [
        { crit_dmg: 20 }, // R1
        { crit_dmg: 25 }, // R2
        { crit_dmg: 30 }, // R3
        { crit_dmg: 35 }, // R4
        { crit_dmg: 40 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_absolution",
      serializeId: 1,
      title: "talent_name.weapon_absolution",
      description: "talent_descr.weapon_absolution_2",
      maxStacks: 3,
      refinementStats: [
        { dmg_all: 16 }, // R1
        { dmg_all: 20 }, // R2
        { dmg_all: 24 }, // R3
        { dmg_all: 28 }, // R4
        { dmg_all: 32 }, // R5
      ],
    },
  ],
};
