// GENERATED by gen-armory.mjs — do not edit
/**
 * amenoma_kageuchi — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/AmenomaKageuchi.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { AmenomaKageuchiStatTable } from "../generated/weaponStatTables.js";

export const amenomaKageuchi: DbObjectWeapon = {
  name: "amenoma_kageuchi",
  serializeId: 100,
  gameId: 11414,
  rarity: 4,
  weapon: "sword",
  statTable: AmenomaKageuchiStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_amenoma_kageuta_blade",
      description: "talent_descr.weapon_amenoma_kageuta_blade",
      refinementStats: [

      ],
    },
  ],
};
