// GENERATED by gen-armory.mjs — do not edit
/**
 * amos_bow — 5★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/AmosBow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { AmosBowStatTable } from "../generated/weaponStatTables.js";

export const amosBow: DbObjectWeapon = {
  name: "amos_bow",
  serializeId: 24,
  gameId: 15502,
  rarity: 5,
  weapon: "bow",
  statTable: AmosBowStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_amos_bow",
      description: "talent_descr.weapon_amos_bow_passive",
      refinementStats: [
        { dmg_normal: 12, dmg_charged: 12 }, // R1
        { dmg_normal: 15, dmg_charged: 15 }, // R2
        { dmg_normal: 18, dmg_charged: 18 }, // R3
        { dmg_normal: 21, dmg_charged: 21 }, // R4
        { dmg_normal: 24, dmg_charged: 24 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_amos_bow",
      serializeId: 1,
      title: "talent_name.weapon_amos_bow",
      description: "talent_descr.weapon_amos_bow",
      maxStacks: 5,
      refinementStats: [
        { dmg_normal: 8, dmg_charged: 8 }, // R1
        { dmg_normal: 10, dmg_charged: 10 }, // R2
        { dmg_normal: 12, dmg_charged: 12 }, // R3
        { dmg_normal: 14, dmg_charged: 14 }, // R4
        { dmg_normal: 16, dmg_charged: 16 }, // R5
      ],
    },
  ],
};
