// GENERATED by gen-armory.mjs — do not edit
/**
 * aqua_simulacra — 5★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/AquaSimulacra.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { AquaSimulacraStatTable } from "../generated/weaponStatTables.js";

export const aquaSimulacra: DbObjectWeapon = {
  name: "aqua_simulacra",
  serializeId: 122,
  gameId: 15508,
  rarity: 5,
  weapon: "bow",
  statTable: AquaSimulacraStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.aqua_simulacra",
      description: "talent_descr.aqua_simulacra_1",
      refinementStats: [
        { hp_percent: 16 }, // R1
        { hp_percent: 20 }, // R2
        { hp_percent: 24 }, // R3
        { hp_percent: 28 }, // R4
        { hp_percent: 32 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_aqua_simulacra",
      serializeId: 1,
      title: "talent_name.aqua_simulacra",
      description: "talent_descr.aqua_simulacra_2",
      refinementStats: [
        { dmg_all: 20 }, // R1
        { dmg_all: 25 }, // R2
        { dmg_all: 30 }, // R3
        { dmg_all: 35 }, // R4
        { dmg_all: 40 }, // R5
      ],
    },
  ],
};
