// GENERATED by gen-armory.mjs — do not edit
/**
 * azurelight — 5★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/Azurelight.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { AzurelightStatTable } from "../generated/weaponStatTables.js";

export const azurelight: DbObjectWeapon = {
  name: "azurelight",
  serializeId: 201,
  gameId: 11517,
  rarity: 5,
  weapon: "sword",
  statTable: AzurelightStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_azurelight_1",
      serializeId: 1,
      title: "talent_name.weapon_azurelight",
      description: "talent_descr.weapon_azurelight",
      refinementStats: [
        { atk_percent: 24 }, // R1
        { atk_percent: 30 }, // R2
        { atk_percent: 36 }, // R3
        { atk_percent: 42 }, // R4
        { atk_percent: 48 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_azurelight_2",
      serializeId: 2,
      title: "talent_name.weapon_azurelight",
      description: "talent_descr.weapon_azurelight_2",
      refinementStats: [
        { atk_percent: 24, crit_dmg: 40 }, // R1
        { atk_percent: 30, crit_dmg: 50 }, // R2
        { atk_percent: 36, crit_dmg: 60 }, // R3
        { atk_percent: 42, crit_dmg: 70 }, // R4
        { atk_percent: 48, crit_dmg: 80 }, // R5
      ],
      condition: {
        type: "boolean",
        name: "weapon_azurelight_1",
      },
    },
  ],
};
