// GENERATED by gen-armory.mjs — do not edit
/**
 * ballad_of_the_boundless_blue — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/BalladoftheBoundlessBlue.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { BalladoftheBoundlessBlueStatTable } from "../generated/weaponStatTables.js";

export const balladOfTheBoundlessBlue: DbObjectWeapon = {
  name: "ballad_of_the_boundless_blue",
  serializeId: 162,
  gameId: 14426,
  rarity: 4,
  weapon: "catalyst",
  statTable: BalladoftheBoundlessBlueStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_azure_skies",
      serializeId: 1,
      title: "talent_name.weapon_azure_skies",
      description: "talent_descr.weapon_azure_skies",
      maxStacks: 3,
      refinementStats: [
        { dmg_normal: 8, dmg_charged: 6 }, // R1
        { dmg_normal: 10, dmg_charged: 7.5 }, // R2
        { dmg_normal: 12, dmg_charged: 9 }, // R3
        { dmg_normal: 14, dmg_charged: 10.5 }, // R4
        { dmg_normal: 16, dmg_charged: 12 }, // R5
      ],
    },
  ],
};
