// GENERATED by gen-armory.mjs — do not edit
/**
 * blackcliff_longsword — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/BlackcliffLongsword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { BlackcliffLongswordStatTable } from "../generated/weaponStatTables.js";

export const blackcliffLongsword: DbObjectWeapon = {
  name: "blackcliff_longsword",
  serializeId: 3,
  gameId: 11408,
  rarity: 4,
  weapon: "sword",
  statTable: BlackcliffLongswordStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_blackcliff_longsword",
      serializeId: 1,
      title: "talent_name.weapon_press_the_advantage",
      description: "talent_descr.weapon_press_the_advantage",
      maxStacks: 3,
      refinementStats: [
        { atk_percent: 12 }, // R1
        { atk_percent: 15 }, // R2
        { atk_percent: 18 }, // R3
        { atk_percent: 21 }, // R4
        { atk_percent: 24 }, // R5
      ],
    },
  ],
};
