// GENERATED by gen-armory.mjs — do not edit
/**
 * blackcliff_agate — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/BlackcliffAgate.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { BlackcliffAgateStatTable } from "../generated/weaponStatTables.js";

export const blackcliffAgate: DbObjectWeapon = {
  name: "blackcliff_agate",
  serializeId: 56,
  gameId: 14408,
  rarity: 4,
  weapon: "catalyst",
  statTable: BlackcliffAgateStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_blackcliff_agate",
      serializeId: 1,
      title: "talent_name.weapon_press_the_advantage",
      description: "talent_descr.weapon_press_the_advantage",
      maxStacks: 3,
      refinementStats: [
        { atk_percent: 12 }, // R1
        { atk_percent: 15 }, // R2
        { atk_percent: 18 }, // R3
        { atk_percent: 21 }, // R4
        { atk_percent: 24 }, // R5
      ],
    },
  ],
};
