// GENERATED by gen-armory.mjs — do not edit
/**
 * blackcliff_warbow — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/BlackcliffWarbow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { BlackcliffWarbowStatTable } from "../generated/weaponStatTables.js";

export const blackcliffWarbow: DbObjectWeapon = {
  name: "blackcliff_warbow",
  serializeId: 25,
  gameId: 15408,
  rarity: 4,
  weapon: "bow",
  statTable: BlackcliffWarbowStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_blackcliff_warbow",
      serializeId: 1,
      title: "talent_name.weapon_press_the_advantage",
      description: "talent_descr.weapon_press_the_advantage",
      maxStacks: 3,
      refinementStats: [
        { atk_percent: 12 }, // R1
        { atk_percent: 15 }, // R2
        { atk_percent: 18 }, // R3
        { atk_percent: 21 }, // R4
        { atk_percent: 24 }, // R5
      ],
    },
  ],
};
