// GENERATED by gen-armory.mjs — do not edit
/**
 * brief_pavilion_chatter — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/BriefPavilionChatter.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { BriefPavilionChatterStatTable } from "../generated/weaponStatTables.js";

export const briefPavilionChatter: DbObjectWeapon = {
  name: "brief_pavilion_chatter",
  serializeId: 197,
  gameId: 13432,
  rarity: 4,
  weapon: "polearm",
  statTable: BriefPavilionChatterStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_brief_pavilion_chatter",
      serializeId: 1,
      title: "talent_name.weapon_brief_pavilion_chatter",
      description: "talent_descr.weapon_brief_pavilion_chatter",
      refinementStats: [
        { atk_percent: 20, move_speed: 10 }, // R1
        { atk_percent: 25, move_speed: 10 }, // R2
        { atk_percent: 30, move_speed: 10 }, // R3
        { atk_percent: 35, move_speed: 10 }, // R4
        { atk_percent: 40, move_speed: 10 }, // R5
      ],
    },
  ],
};
