// GENERATED by gen-armory.mjs — do not edit
/**
 * cashflow_supervision — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/CashflowSupervision.js
 *
 * Passive: Golden Supervision
 *   - ConditionStaticRefine (always-on):
 *       ATK% at R1..R5: [16, 20, 24, 28, 32]
 *   - ConditionStacks (name: "weapon_cashflow_supervision", maxStacks: 3):
 *       Per-stack dmg_normal + dmg_charged at R1..R5:
 *         dmg_normal:  [16, 20, 24, 28, 32]
 *         dmg_charged: [14, 17.5, 21, 24.5, 28]
 *   - ConditionBooleanValue (setting: "weapon_cashflow_supervision", cond: ge, value: 3):
 *       At max stacks only carries atk_speed_normal (display-only) — OMITTED (no damage contribution).
 *
 * Oracle passiveToggles: { weapon_cashflow_supervision: 3 } (max stacks active)
 * Real damage = StaticRefine atk% + Stacks × (dmg_normal + dmg_charged)
 */

import type { DbObjectWeapon } from "@genshin/types";
import { CashflowSupervisionStatTable } from "../generated/weaponStatTables.js";

export const cashflowSupervision: DbObjectWeapon = {
  name: "cashflow_supervision",
  serializeId: 163,
  gameId: 14513,
  rarity: 5,
  weapon: "catalyst",
  statTable: CashflowSupervisionStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_cashflow_supervision",
      description: "talent_descr.weapon_cashflow_supervision_1",
      refinementStats: [
        { atk_percent: 16 }, // R1
        { atk_percent: 20 }, // R2
        { atk_percent: 24 }, // R3
        { atk_percent: 28 }, // R4
        { atk_percent: 32 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_cashflow_supervision",
      serializeId: 1,
      title: "talent_name.weapon_cashflow_supervision",
      description: "talent_descr.weapon_cashflow_supervision_2",
      maxStacks: 3,
      refinementStats: [
        { dmg_normal: 16, dmg_charged: 14 },    // R1
        { dmg_normal: 20, dmg_charged: 17.5 },  // R2
        { dmg_normal: 24, dmg_charged: 21 },    // R3
        { dmg_normal: 28, dmg_charged: 24.5 },  // R4
        { dmg_normal: 32, dmg_charged: 28 },    // R5
      ],
    },
    // ConditionBooleanValue at max stacks only carries atk_speed_normal (display-only) — omitted.
  ],
};
