// GENERATED by gen-armory.mjs — do not edit
/**
 * cloudforged — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/Cloudforged.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { CloudforgedStatTable } from "../generated/weaponStatTables.js";

export const cloudforged: DbObjectWeapon = {
  name: "cloudforged",
  serializeId: 174,
  gameId: 15426,
  rarity: 4,
  weapon: "bow",
  statTable: CloudforgedStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_cloudforged",
      serializeId: 1,
      title: "talent_name.weapon_cloudforged",
      description: "talent_descr.weapon_cloudforged",
      maxStacks: 2,
      refinementStats: [
        { mastery: 40 }, // R1
        { mastery: 50 }, // R2
        { mastery: 60 }, // R3
        { mastery: 70 }, // R4
        { mastery: 80 }, // R5
      ],
    },
  ],
};
