// GENERATED by gen-armory.mjs — do not edit
/**
 * compound_bow — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/CompoundBow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { CompoundBowStatTable } from "../generated/weaponStatTables.js";

export const compoundBow: DbObjectWeapon = {
  name: "compound_bow",
  serializeId: 26,
  gameId: 15407,
  rarity: 4,
  weapon: "bow",
  statTable: CompoundBowStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_compound_bow",
      serializeId: 1,
      title: "talent_name.weapon_compound_bow",
      description: "talent_descr.weapon_compound_bow",
      maxStacks: 4,
      refinementStats: [
        { atk_percent: 4, atk_speed_normal: 1.2 }, // R1
        { atk_percent: 5, atk_speed_normal: 1.5 }, // R2
        { atk_percent: 6, atk_speed_normal: 1.8 }, // R3
        { atk_percent: 7, atk_speed_normal: 2.1 }, // R4
        { atk_percent: 8, atk_speed_normal: 2.4 }, // R5
      ],
    },
  ],
};
