// GENERATED by gen-armory.mjs — do not edit
/**
 * cranes_echoing_call — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/CranesEchoingCall.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { CranesEchoingCallStatTable } from "../generated/weaponStatTables.js";

export const cranesEchoingCall: DbObjectWeapon = {
  name: "cranes_echoing_call",
  serializeId: 169,
  gameId: 14515,
  rarity: 5,
  weapon: "catalyst",
  statTable: CranesEchoingCallStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_cranes_echoing_call",
      serializeId: 1,
      title: "talent_name.weapon_cranes_echoing_call",
      description: "talent_descr.weapon_cranes_echoing_call_1",
      refinementStats: [
        { dmg_plunge: 28 }, // R1
        { dmg_plunge: 41 }, // R2
        { dmg_plunge: 54 }, // R3
        { dmg_plunge: 67 }, // R4
        { dmg_plunge: 80 }, // R5
      ],
    },
    {
      type: "refine",
      title: "talent_name.weapon_cranes_echoing_call",
      description: "talent_descr.weapon_cranes_echoing_call_2",
      refinementStats: [

      ],
    },
  ],
};
