// GENERATED by gen-armory.mjs — do not edit
/**
 * dark_iron_sword — 3★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/DarkIronSword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { DarkIronSwordStatTable } from "../generated/weaponStatTables.js";

export const darkIronSword: DbObjectWeapon = {
  name: "dark_iron_sword",
  serializeId: 6,
  gameId: 11304,
  rarity: 3,
  weapon: "sword",
  statTable: DarkIronSwordStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_dark_iron_sword",
      serializeId: 1,
      title: "talent_name.weapon_dark_iron_sword",
      description: "talent_descr.weapon_dark_iron_sword",
      refinementStats: [
        { atk_percent: 20 }, // R1
        { atk_percent: 25 }, // R2
        { atk_percent: 30 }, // R3
        { atk_percent: 35 }, // R4
        { atk_percent: 40 }, // R5
      ],
    },
  ],
};
