// GENERATED by gen-armory.mjs — do not edit
/**
 * deathmatch — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/Deathmatch.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { DeathmatchStatTable } from "../generated/weaponStatTables.js";

export const deathmatch: DbObjectWeapon = {
  name: "deathmatch",
  serializeId: 87,
  gameId: 13405,
  rarity: 4,
  weapon: "polearm",
  statTable: DeathmatchStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_deathmatch_1",
      description: "talent_descr.weapon_deathmatch_1",
      refinementStats: [
        { atk_percent: 16, def_percent: 16 }, // R1
        { atk_percent: 20, def_percent: 20 }, // R2
        { atk_percent: 24, def_percent: 24 }, // R3
        { atk_percent: 28, def_percent: 28 }, // R4
        { atk_percent: 32, def_percent: 32 }, // R5
      ],
      condition: {
        type: "boolean",
        name: "weapon_deathmatch",
        invert: true,
      },
    },
    {
      type: "boolean-refine",
      name: "weapon_deathmatch",
      serializeId: 1,
      title: "talent_name.weapon_deathmatch_2",
      description: "talent_descr.weapon_deathmatch_2",
      refinementStats: [
        { atk_percent: 24 }, // R1
        { atk_percent: 30 }, // R2
        { atk_percent: 36 }, // R3
        { atk_percent: 42 }, // R4
        { atk_percent: 48 }, // R5
      ],
    },
  ],
};
