// GENERATED by gen-armory.mjs — do not edit
/**
 * dodoco_tales — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/DodocoTales.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { DodocoTalesStatTable } from "../generated/weaponStatTables.js";

export const dodocoTales: DbObjectWeapon = {
  name: "dodoco_tales",
  serializeId: 99,
  gameId: 14413,
  rarity: 4,
  weapon: "catalyst",
  statTable: DodocoTalesStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_dodoco_tales_1",
      serializeId: 1,
      title: "talent_name.weapon_dodoco_tales",
      description: "talent_descr.weapon_dodoco_tales_1",
      refinementStats: [
        { dmg_charged: 16 }, // R1
        { dmg_charged: 20 }, // R2
        { dmg_charged: 24 }, // R3
        { dmg_charged: 28 }, // R4
        { dmg_charged: 32 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_dodoco_tales_2",
      serializeId: 2,
      title: "talent_name.weapon_dodoco_tales",
      description: "talent_descr.weapon_dodoco_tales_2",
      refinementStats: [
        { atk_percent: 8 }, // R1
        { atk_percent: 10 }, // R2
        { atk_percent: 12 }, // R3
        { atk_percent: 14 }, // R4
        { atk_percent: 16 }, // R5
      ],
    },
  ],
};
