// GENERATED by gen-armory.mjs — do not edit
/**
 * earthshaker — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/Earthshaker.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { EarthshakerStatTable } from "../generated/weaponStatTables.js";

export const earthshaker: DbObjectWeapon = {
  name: "earthshaker",
  serializeId: 182,
  gameId: 12431,
  rarity: 4,
  weapon: "claymore",
  statTable: EarthshakerStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_earthshaker",
      serializeId: 1,
      title: "talent_name.weapon_earthshaker",
      description: "talent_descr.weapon_earthshaker",
      refinementStats: [
        { dmg_skill: 16 }, // R1
        { dmg_skill: 20 }, // R2
        { dmg_skill: 24 }, // R3
        { dmg_skill: 28 }, // R4
        { dmg_skill: 32 }, // R5
      ],
    },
  ],
};
