// GENERATED by gen-armory.mjs — do not edit
/**
 * emerald_orb — 3★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/EmeraldOrb.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { EmeraldOrbStatTable } from "../generated/weaponStatTables.js";

export const emeraldOrb: DbObjectWeapon = {
  name: "emerald_orb",
  serializeId: 61,
  gameId: 14304,
  rarity: 3,
  weapon: "catalyst",
  statTable: EmeraldOrbStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_emerald_orb",
      serializeId: 1,
      title: "talent_name.weapon_emerald_orb",
      description: "talent_descr.weapon_emerald_orb",
      refinementStats: [
        { atk_percent: 20 }, // R1
        { atk_percent: 25 }, // R2
        { atk_percent: 30 }, // R3
        { atk_percent: 35 }, // R4
        { atk_percent: 40 }, // R5
      ],
    },
  ],
};
