// GENERATED by gen-armory.mjs — do not edit
/**
 * fading_twilight — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/FadingTwilight.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FadingTwilightStatTable } from "../generated/weaponStatTables.js";

export const fadingTwilight: DbObjectWeapon = {
  name: "fading_twilight",
  serializeId: 123,
  gameId: 15411,
  rarity: 4,
  weapon: "bow",
  statTable: FadingTwilightStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_fading_twilight_1",
      serializeId: 1,
      title: "talent_name.weapon_fading_twilight_1",
      description: "talent_descr.weapon_fading_twilight_dmg",
      refinementStats: [
        { dmg_all: 6 }, // R1
        { dmg_all: 7.5 }, // R2
        { dmg_all: 9 }, // R3
        { dmg_all: 10.5 }, // R4
        { dmg_all: 12 }, // R5
      ],
      condition: {
        type: "and",
        items: [
          {
            type: "boolean",
            name: "weapon_fading_twilight_2",
            invert: true,
          },
          {
            type: "boolean",
            name: "weapon_fading_twilight_3",
            invert: true,
          },
        ],
      },
    },
    {
      type: "boolean-refine",
      name: "weapon_fading_twilight_2",
      serializeId: 2,
      title: "talent_name.weapon_fading_twilight_2",
      description: "talent_descr.weapon_fading_twilight_dmg",
      refinementStats: [
        { dmg_all: 10 }, // R1
        { dmg_all: 12.5 }, // R2
        { dmg_all: 17 }, // R3
        { dmg_all: 17.5 }, // R4
        { dmg_all: 20 }, // R5
      ],
      condition: {
        type: "and",
        items: [
          {
            type: "boolean",
            name: "weapon_fading_twilight_1",
            invert: true,
          },
          {
            type: "boolean",
            name: "weapon_fading_twilight_3",
            invert: true,
          },
        ],
      },
    },
    {
      type: "boolean-refine",
      name: "weapon_fading_twilight_3",
      serializeId: 3,
      title: "talent_name.weapon_fading_twilight_3",
      description: "talent_descr.weapon_fading_twilight_dmg",
      refinementStats: [
        { dmg_all: 14 }, // R1
        { dmg_all: 17.5 }, // R2
        { dmg_all: 21 }, // R3
        { dmg_all: 24.5 }, // R4
        { dmg_all: 28 }, // R5
      ],
      condition: {
        type: "and",
        items: [
          {
            type: "boolean",
            name: "weapon_fading_twilight_1",
            invert: true,
          },
          {
            type: "boolean",
            name: "weapon_fading_twilight_2",
            invert: true,
          },
        ],
      },
    },
  ],
};
