// GENERATED by gen-armory.mjs — do not edit
/**
 * favonius_warbow — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/FavoniusWarbow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FavoniusWarbowStatTable } from "../generated/weaponStatTables.js";

export const favoniusWarbow: DbObjectWeapon = {
  name: "favonius_warbow",
  serializeId: 28,
  gameId: 15401,
  rarity: 4,
  weapon: "bow",
  statTable: FavoniusWarbowStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_favonoius_passive",
      description: "talent_descr.weapon_favonoius_passive",
      refinementStats: [

      ],
    },
  ],
};
