// GENERATED by gen-armory.mjs — do not edit
/**
 * favonius_lance — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/FavoniusLance.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FavoniusLanceStatTable } from "../generated/weaponStatTables.js";

export const favoniusLance: DbObjectWeapon = {
  name: "favonius_lance",
  serializeId: 90,
  gameId: 13407,
  rarity: 4,
  weapon: "polearm",
  statTable: FavoniusLanceStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_favonoius_passive",
      description: "talent_descr.weapon_favonoius_passive",
      refinementStats: [

      ],
    },
  ],
};
