// GENERATED by gen-armory.mjs — do not edit
/**
 * favonius_codex — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/FavoniusCodex.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FavoniusCodexStatTable } from "../generated/weaponStatTables.js";

export const favoniusCodex: DbObjectWeapon = {
  name: "favonius_codex",
  serializeId: 55,
  gameId: 14401,
  rarity: 4,
  weapon: "catalyst",
  statTable: FavoniusCodexStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_favonoius_passive",
      description: "talent_descr.weapon_favonoius_passive",
      refinementStats: [

      ],
    },
  ],
};
