// GENERATED by gen-armory.mjs — do not edit
/**
 * favonius_sword — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/FavoniusSword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FavoniusSwordStatTable } from "../generated/weaponStatTables.js";

export const favoniusSword: DbObjectWeapon = {
  name: "favonius_sword",
  serializeId: 7,
  gameId: 11401,
  rarity: 4,
  weapon: "sword",
  statTable: FavoniusSwordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_favonoius_passive",
      description: "talent_descr.weapon_favonoius_passive",
      refinementStats: [

      ],
    },
  ],
};
