// GENERATED by gen-armory.mjs — do not edit
/**
 * favonius_greatsword — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/FavoniusGreatsword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FavoniusGreatswordStatTable } from "../generated/weaponStatTables.js";

export const favoniusGreatsword: DbObjectWeapon = {
  name: "favonius_greatsword",
  serializeId: 66,
  gameId: 12401,
  rarity: 4,
  weapon: "claymore",
  statTable: FavoniusGreatswordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_favonoius_passive",
      description: "talent_descr.weapon_favonoius_passive",
      refinementStats: [

      ],
    },
  ],
};
