// GENERATED by gen-armory.mjs — do not edit
/**
 * ferrous_shadow — 3★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/FerrousShadow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FerrousShadowStatTable } from "../generated/weaponStatTables.js";

export const ferrousShadow: DbObjectWeapon = {
  name: "ferrous_shadow",
  serializeId: 77,
  gameId: 12301,
  rarity: 3,
  weapon: "claymore",
  statTable: FerrousShadowStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_ferrous_shadow",
      serializeId: 1,
      title: "talent_name.weapon_unbending",
      description: "talent_descr.weapon_unbending",
      refinementStats: [
        { dmg_charged: 30 }, // R1
        { dmg_charged: 35 }, // R2
        { dmg_charged: 40 }, // R3
        { dmg_charged: 45 }, // R4
        { dmg_charged: 50 }, // R5
      ],
    },
  ],
};
