// GENERATED by gen-armory.mjs — do not edit
/**
 * festering_desire — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/FesteringDesire.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FesteringDesireStatTable } from "../generated/weaponStatTables.js";

export const festeringDesire: DbObjectWeapon = {
  name: "festering_desire",
  serializeId: 8,
  gameId: 11413,
  rarity: 4,
  weapon: "sword",
  statTable: FesteringDesireStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_festering_desire",
      description: "talent_descr.weapon_festering_desire",
      refinementStats: [
        { dmg_skill: 16, crit_rate_skill: 6 }, // R1
        { dmg_skill: 20, crit_rate_skill: 7.5 }, // R2
        { dmg_skill: 24, crit_rate_skill: 9 }, // R3
        { dmg_skill: 28, crit_rate_skill: 10.5 }, // R4
        { dmg_skill: 32, crit_rate_skill: 12 }, // R5
      ],
    },
  ],
};
