// GENERATED by gen-armory.mjs — do not edit
/**
 * flamebreath_flute — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/FlamebreathFlute.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FlamebreathFluteStatTable } from "../generated/weaponStatTables.js";

export const flamebreathFlute: DbObjectWeapon = {
  name: "flamebreath_flute",
  serializeId: 184,
  gameId: 11431,
  rarity: 4,
  weapon: "sword",
  statTable: FlamebreathFluteStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_flamebreath_flute",
      serializeId: 1,
      title: "talent_name.weapon_flamebreath_flute",
      description: "talent_descr.weapon_flamebreath_flute",
      refinementStats: [
        { def_percent: 16 }, // R1
        { def_percent: 20 }, // R2
        { def_percent: 24 }, // R3
        { def_percent: 28 }, // R4
        { def_percent: 32 }, // R5
      ],
    },
  ],
};
