// GENERATED by gen-armory.mjs — do not edit
/**
 * flame_forged_insight — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/FlameForgedInsight.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FlameForgedInsightStatTable } from "../generated/weaponStatTables.js";

export const flameForgedInsight: DbObjectWeapon = {
  name: "flame_forged_insight",
  serializeId: 223,
  gameId: 12432,
  rarity: 4,
  weapon: "claymore",
  statTable: FlameForgedInsightStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_flame_forged_insight",
      serializeId: 1,
      title: "talent_name.weapon_flame_forged_insight",
      description: "talent_descr.weapon_flame_forged_insight",
      refinementStats: [
        { mastery: 60 }, // R1
        { mastery: 75 }, // R2
        { mastery: 90 }, // R3
        { mastery: 105 }, // R4
        { mastery: 120 }, // R5
      ],
    },
  ],
};
