// GENERATED by gen-armory.mjs — do not edit
/**
 * fleuve_cendre_ferryman — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/FleuveCendreFerryman.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FleuveCendreFerrymanStatTable } from "../generated/weaponStatTables.js";

export const fleuveCendreFerryman: DbObjectWeapon = {
  name: "fleuve_cendre_ferryman",
  serializeId: 148,
  gameId: 11426,
  rarity: 4,
  weapon: "sword",
  statTable: FleuveCendreFerrymanStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_fleuve_cendre_ferryman",
      description: "talent_descr.weapon_fleuve_cendre_ferryman_1",
      refinementStats: [
        { crit_rate_skill: 8 }, // R1
        { crit_rate_skill: 10 }, // R2
        { crit_rate_skill: 12 }, // R3
        { crit_rate_skill: 14 }, // R4
        { crit_rate_skill: 16 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_fleuve_cendre_ferryman",
      serializeId: 1,
      title: "talent_name.weapon_fleuve_cendre_ferryman",
      description: "talent_descr.weapon_fleuve_cendre_ferryman_2",
      refinementStats: [
        { recharge: 16 }, // R1
        { recharge: 20 }, // R2
        { recharge: 24 }, // R3
        { recharge: 28 }, // R4
        { recharge: 32 }, // R5
      ],
    },
  ],
};
