// GENERATED by gen-armory.mjs — do not edit
/**
 * flower_wreathed_feathers — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/FlowerWreathedFeathers.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FlowerWreathedFeathersStatTable } from "../generated/weaponStatTables.js";

export const flowerWreathedFeathers: DbObjectWeapon = {
  name: "flower_wreathed_feathers",
  serializeId: 189,
  gameId: 15430,
  rarity: 4,
  weapon: "bow",
  statTable: FlowerWreathedFeathersStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.flower_wreathed_feathers",
      description: "talent_descr.flower_wreathed_feathers_1",
      refinementStats: [

      ],
    },
    {
      type: "stacks",
      name: "flower_wreathed_feathers",
      serializeId: 1,
      title: "talent_name.flower_wreathed_feathers",
      description: "talent_descr.flower_wreathed_feathers_2",
      maxStacks: 6,
      refinementStats: [
        { dmg_charged: 6 }, // R1
        { dmg_charged: 7.5 }, // R2
        { dmg_charged: 9 }, // R3
        { dmg_charged: 10.5 }, // R4
        { dmg_charged: 12 }, // R5
      ],
    },
  ],
};
