// GENERATED by gen-armory.mjs — do not edit
/**
 * forest_regalia — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/ForestRegalia.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { ForestRegaliaStatTable } from "../generated/weaponStatTables.js";

export const forestRegalia: DbObjectWeapon = {
  name: "forest_regalia",
  serializeId: 127,
  gameId: 12417,
  rarity: 4,
  weapon: "claymore",
  statTable: ForestRegaliaStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_forest_sanctuary",
      serializeId: 1,
      title: "talent_name.forest_sanctuary",
      description: "talent_descr.forest_sanctuary",
      refinementStats: [
        { mastery: 60 }, // R1
        { mastery: 75 }, // R2
        { mastery: 90 }, // R3
        { mastery: 105 }, // R4
        { mastery: 120 }, // R5
      ],
    },
  ],
};
