// GENERATED by gen-armory.mjs — do not edit
/**
 * fractured_halo — 5★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/FracturedHalo.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FracturedHaloStatTable } from "../generated/weaponStatTables.js";

export const fracturedHalo: DbObjectWeapon = {
  name: "fractured_halo",
  serializeId: 222,
  gameId: 13515,
  rarity: 5,
  weapon: "polearm",
  statTable: FracturedHaloStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "talent_name.weapon_fractured_halo_1",
      serializeId: 1,
      title: "talent_name.weapon_fractured_halo",
      description: "talent_descr.weapon_fractured_halo_1",
      refinementStats: [
        { atk_percent: 24 }, // R1
        { atk_percent: 30 }, // R2
        { atk_percent: 36 }, // R3
        { atk_percent: 42 }, // R4
        { atk_percent: 48 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "talent_name.weapon_fractured_halo_2",
      serializeId: 2,
      title: "talent_name.weapon_fractured_halo",
      description: "talent_descr.weapon_fractured_halo_2",
      refinementStats: [
        { dmg_reaction_lunarcharged: 40 }, // R1
        { dmg_reaction_lunarcharged: 50 }, // R2
        { dmg_reaction_lunarcharged: 60 }, // R3
        { dmg_reaction_lunarcharged: 70 }, // R4
        { dmg_reaction_lunarcharged: 80 }, // R5
      ],
    },
  ],
};
