// GENERATED by gen-armory.mjs — do not edit
/**
 * fruitful_hook — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/FruitfulHook.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FruitfulHookStatTable } from "../generated/weaponStatTables.js";

export const fruitfulHook: DbObjectWeapon = {
  name: "fruitful_hook",
  serializeId: 188,
  gameId: 12430,
  rarity: 4,
  weapon: "claymore",
  statTable: FruitfulHookStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_fruitful_hook",
      description: "talent_descr.weapon_fruitful_hook_1",
      refinementStats: [
        { crit_rate_plunge: 16 }, // R1
        { crit_rate_plunge: 20 }, // R2
        { crit_rate_plunge: 24 }, // R3
        { crit_rate_plunge: 28 }, // R4
        { crit_rate_plunge: 32 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_fruitful_hook",
      serializeId: 1,
      title: "talent_name.weapon_fruitful_hook",
      description: "talent_descr.weapon_fruitful_hook_2",
      refinementStats: [
        { dmg_normal: 16, dmg_charged: 16, dmg_plunge: 16 }, // R1
        { dmg_normal: 20, dmg_charged: 20, dmg_plunge: 20 }, // R2
        { dmg_normal: 24, dmg_charged: 24, dmg_plunge: 24 }, // R3
        { dmg_normal: 28, dmg_charged: 28, dmg_plunge: 28 }, // R4
        { dmg_normal: 32, dmg_charged: 32, dmg_plunge: 32 }, // R5
      ],
    },
  ],
};
