// GENERATED by gen-armory.mjs — do not edit
/**
 * fruit_of_fulfillment — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/FruitOfFulfillment.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { FruitOfFulfillmentStatTable } from "../generated/weaponStatTables.js";

export const fruitOfFulfillment: DbObjectWeapon = {
  name: "fruit_of_fulfillment",
  serializeId: 131,
  gameId: 14417,
  rarity: 4,
  weapon: "catalyst",
  statTable: FruitOfFulfillmentStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_fruit_of_fulfillment",
      serializeId: 1,
      title: "talent_name.full_circle",
      description: "talent_descr.full_circle",
      maxStacks: 5,
      refinementStats: [
        { mastery: 24, atk_percent: -5 }, // R1
        { mastery: 27, atk_percent: -5 }, // R2
        { mastery: 30, atk_percent: -5 }, // R3
        { mastery: 33, atk_percent: -5 }, // R4
        { mastery: 36, atk_percent: -5 }, // R5
      ],
    },
  ],
};
