// GENERATED by gen-armory.mjs — do not edit
/**
 * hamayumi — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/Hamayumi.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { HamayumiStatTable } from "../generated/weaponStatTables.js";

export const hamayumi: DbObjectWeapon = {
  name: "hamayumi",
  serializeId: 106,
  gameId: 15414,
  rarity: 4,
  weapon: "bow",
  statTable: HamayumiStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_demon_slayer_bow",
      description: "talent_descr.weapon_demon_slayer_bow_1",
      refinementStats: [
        { dmg_normal: 16, dmg_charged: 12 }, // R1
        { dmg_normal: 20, dmg_charged: 15 }, // R2
        { dmg_normal: 24, dmg_charged: 18 }, // R3
        { dmg_normal: 28, dmg_charged: 21 }, // R4
        { dmg_normal: 32, dmg_charged: 24 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_demon_slayer_bow",
      serializeId: 1,
      title: "talent_name.weapon_demon_slayer_bow",
      description: "talent_descr.weapon_demon_slayer_bow_2",
      refinementStats: [
        { dmg_normal: 16, dmg_charged: 12 }, // R1
        { dmg_normal: 20, dmg_charged: 15 }, // R2
        { dmg_normal: 24, dmg_charged: 18 }, // R3
        { dmg_normal: 28, dmg_charged: 21 }, // R4
        { dmg_normal: 32, dmg_charged: 24 }, // R5
      ],
    },
  ],
};
