// GENERATED by gen-armory.mjs — do not edit
/**
 * haran_geppaku_futsu — 5★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/HaranGeppakuFutsu.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { HaranGeppakuFutsuStatTable } from "../generated/weaponStatTables.js";

export const haranGeppakuFutsu: DbObjectWeapon = {
  name: "haran_geppaku_futsu",
  serializeId: 121,
  gameId: 11510,
  rarity: 5,
  weapon: "sword",
  statTable: HaranGeppakuFutsuStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.haran_geppaku_futsu",
      description: "talent_descr.haran_geppaku_futsu_1",
      refinementStats: [
        { dmg_anemo: 12, dmg_geo: 12, dmg_pyro: 12, dmg_electro: 12, dmg_hydro: 12, dmg_cryo: 12, dmg_dendro: 12 }, // R1
        { dmg_anemo: 15, dmg_geo: 15, dmg_pyro: 15, dmg_electro: 15, dmg_hydro: 15, dmg_cryo: 15, dmg_dendro: 15 }, // R2
        { dmg_anemo: 18, dmg_geo: 18, dmg_pyro: 18, dmg_electro: 18, dmg_hydro: 18, dmg_cryo: 18, dmg_dendro: 18 }, // R3
        { dmg_anemo: 21, dmg_geo: 21, dmg_pyro: 21, dmg_electro: 21, dmg_hydro: 21, dmg_cryo: 21, dmg_dendro: 21 }, // R4
        { dmg_anemo: 24, dmg_geo: 24, dmg_pyro: 24, dmg_electro: 24, dmg_hydro: 24, dmg_cryo: 24, dmg_dendro: 24 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "haran_geppaku_futsu",
      serializeId: 1,
      title: "talent_name.haran_geppaku_futsu_2",
      description: "talent_descr.haran_geppaku_futsu_2",
      maxStacks: 2,
      refinementStats: [
        { dmg_normal: 20 }, // R1
        { dmg_normal: 25 }, // R2
        { dmg_normal: 30 }, // R3
        { dmg_normal: 35 }, // R4
        { dmg_normal: 40 }, // R5
      ],
    },
  ],
};
