// GENERATED by gen-armory.mjs — do not edit
/**
 * harbinger_of_dawn — 3★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/HarbingerofDawn.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { HarbingerofDawnStatTable } from "../generated/weaponStatTables.js";

export const harbingerOfDawn: DbObjectWeapon = {
  name: "harbinger_of_dawn",
  serializeId: 11,
  gameId: 11302,
  rarity: 3,
  weapon: "sword",
  statTable: HarbingerofDawnStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_harbinger_of_dawn",
      serializeId: 1,
      title: "talent_name.weapon_harbinger_of_dawn",
      description: "talent_descr.weapon_harbinger_of_dawn",
      refinementStats: [
        { crit_rate: 14 }, // R1
        { crit_rate: 17.5 }, // R2
        { crit_rate: 21 }, // R3
        { crit_rate: 24.5 }, // R4
        { crit_rate: 28 }, // R5
      ],
    },
  ],
};
