// GENERATED by gen-armory.mjs — do not edit
/**
 * ibis_piercer — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/IbisPiercer.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { IbisPiercerStatTable } from "../generated/weaponStatTables.js";

export const ibisPiercer: DbObjectWeapon = {
  name: "ibis_piercer",
  serializeId: 145,
  gameId: 15419,
  rarity: 4,
  weapon: "bow",
  statTable: IbisPiercerStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_ibis_piercer",
      serializeId: 1,
      title: "talent_name.weapon_ibis_piercer",
      description: "talent_descr.weapon_ibis_piercer",
      maxStacks: 2,
      refinementStats: [
        { mastery: 40 }, // R1
        { mastery: 50 }, // R2
        { mastery: 60 }, // R3
        { mastery: 70 }, // R4
        { mastery: 80 }, // R5
      ],
    },
  ],
};
