// GENERATED by gen-armory.mjs — do not edit
/**
 * iron_sting — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/IronSting.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { IronStingStatTable } from "../generated/weaponStatTables.js";

export const ironSting: DbObjectWeapon = {
  name: "iron_sting",
  serializeId: 12,
  gameId: 11407,
  rarity: 4,
  weapon: "sword",
  statTable: IronStingStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_iron_sting",
      serializeId: 1,
      title: "talent_name.weapon_iron_sting",
      description: "talent_descr.weapon_iron_sting",
      maxStacks: 2,
      refinementStats: [
        { dmg_all: 6 }, // R1
        { dmg_all: 7.5 }, // R2
        { dmg_all: 9 }, // R3
        { dmg_all: 10.5 }, // R4
        { dmg_all: 12 }, // R5
      ],
    },
  ],
};
