// GENERATED by gen-armory.mjs — do not edit
/**
 * kaguras_verity — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/KagurasVerity.js
 *
 * Passive: Kagura Dance
 *   - ConditionStacks (name: "weapon_kaguras_verity", maxStacks: 3):
 *       Per-stack dmg_skill at R1..R5: [12, 15, 18, 21, 24]
 *   - ConditionBooleanValue (name: "weapon_kaguras_verity_max_stack",
 *       setting: "weapon_kaguras_verity", cond: ge, value: 3):
 *       At max stacks (3), grant all 7 element dmg bonuses each [12, 15, 18, 21, 24] at R1..R5
 *
 * Oracle passiveToggles: { weapon_kaguras_verity: 3 } (max stacks → both conditions active)
 */

import type { DbObjectWeapon } from "@genshin/types";
import { KagurasVerityStatTable } from "../generated/weaponStatTables.js";

export const kagurasVerity: DbObjectWeapon = {
  name: "kaguras_verity",
  serializeId: 119,
  gameId: 14509,
  rarity: 5,
  weapon: "catalyst",
  statTable: KagurasVerityStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_kaguras_verity",
      serializeId: 1,
      title: "talent_name.weapon_kaguras_verity",
      description: "talent_descr.weapon_kaguras_verity_1",
      maxStacks: 3,
      refinementStats: [
        { dmg_skill: 12 }, // R1
        { dmg_skill: 15 }, // R2
        { dmg_skill: 18 }, // R3
        { dmg_skill: 21 }, // R4
        { dmg_skill: 24 }, // R5
      ],
    },
    {
      type: "boolean-value",
      name: "weapon_kaguras_verity_max_stack",
      title: "talent_name.weapon_kaguras_verity",
      description: "talent_descr.weapon_kaguras_verity_2",
      setting: "weapon_kaguras_verity",
      cond: "ge",
      value: 3,
      refinementStats: [
        { dmg_anemo: 12, dmg_geo: 12, dmg_pyro: 12, dmg_electro: 12, dmg_hydro: 12, dmg_cryo: 12, dmg_dendro: 12 }, // R1
        { dmg_anemo: 15, dmg_geo: 15, dmg_pyro: 15, dmg_electro: 15, dmg_hydro: 15, dmg_cryo: 15, dmg_dendro: 15 }, // R2
        { dmg_anemo: 18, dmg_geo: 18, dmg_pyro: 18, dmg_electro: 18, dmg_hydro: 18, dmg_cryo: 18, dmg_dendro: 18 }, // R3
        { dmg_anemo: 21, dmg_geo: 21, dmg_pyro: 21, dmg_electro: 21, dmg_hydro: 21, dmg_cryo: 21, dmg_dendro: 21 }, // R4
        { dmg_anemo: 24, dmg_geo: 24, dmg_pyro: 24, dmg_electro: 24, dmg_hydro: 24, dmg_cryo: 24, dmg_dendro: 24 }, // R5
      ],
    },
  ],
};
