// GENERATED by gen-armory.mjs — do not edit
/**
 * katsuragikiri_nagamasa — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/KatsuragikiriNagamasa.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { KatsuragikiriNagamasaStatTable } from "../generated/weaponStatTables.js";

export const katsuragikiriNagamasa: DbObjectWeapon = {
  name: "katsuragikiri_nagamasa",
  serializeId: 105,
  gameId: 12414,
  rarity: 4,
  weapon: "claymore",
  statTable: KatsuragikiriNagamasaStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_samurai_conduct",
      description: "talent_descr.weapon_samurai_conduct_1",
      refinementStats: [
        { dmg_skill: 6 }, // R1
        { dmg_skill: 7.5 }, // R2
        { dmg_skill: 9 }, // R3
        { dmg_skill: 10.5 }, // R4
        { dmg_skill: 12 }, // R5
      ],
    },
    {
      type: "refine",
      title: "talent_name.weapon_samurai_conduct",
      description: "talent_descr.weapon_samurai_conduct_2",
      refinementStats: [

      ],
    },
  ],
};
