// GENERATED by gen-armory.mjs — do not edit
/**
 * kitain_cross_spear — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/KitainCrossSpear.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { KitainCrossSpearStatTable } from "../generated/weaponStatTables.js";

export const kitainCrossSpear: DbObjectWeapon = {
  name: "kitain_cross_spear",
  serializeId: 103,
  gameId: 13414,
  rarity: 4,
  weapon: "polearm",
  statTable: KitainCrossSpearStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_samurai_conduct",
      description: "talent_descr.weapon_samurai_conduct_1",
      refinementStats: [
        { dmg_skill: 6 }, // R1
        { dmg_skill: 7.5 }, // R2
        { dmg_skill: 9 }, // R3
        { dmg_skill: 10.5 }, // R4
        { dmg_skill: 12 }, // R5
      ],
    },
    {
      type: "refine",
      title: "talent_name.weapon_samurai_conduct",
      description: "talent_descr.weapon_samurai_conduct_2",
      refinementStats: [

      ],
    },
  ],
};
