// GENERATED by gen-armory.mjs — do not edit
/**
 * lumidouce_elegy — 5★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/LumidouceElegy.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { LumidouceElegyStatTable } from "../generated/weaponStatTables.js";

export const lumidouceElegy: DbObjectWeapon = {
  name: "lumidouce_elegy",
  serializeId: 176,
  gameId: 13513,
  rarity: 5,
  weapon: "polearm",
  statTable: LumidouceElegyStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_lumidouce_elegy",
      description: "talent_descr.weapon_lumidouce_elegy_1",
      refinementStats: [
        { atk_percent: 15 }, // R1
        { atk_percent: 19 }, // R2
        { atk_percent: 23 }, // R3
        { atk_percent: 27 }, // R4
        { atk_percent: 31 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_lumidouce_elegy",
      serializeId: 1,
      title: "talent_name.weapon_lumidouce_elegy",
      description: "talent_descr.weapon_lumidouce_elegy_2",
      maxStacks: 2,
      refinementStats: [
        { dmg_all: 18 }, // R1
        { dmg_all: 23 }, // R2
        { dmg_all: 28 }, // R3
        { dmg_all: 33 }, // R4
        { dmg_all: 38 }, // R5
      ],
    },
  ],
};
