// GENERATED by gen-armory.mjs — do not edit
/**
 * mailed_flower — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/MailedFlower.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MailedFlowerStatTable } from "../generated/weaponStatTables.js";

export const mailedFlower: DbObjectWeapon = {
  name: "mailed_flower",
  serializeId: 142,
  gameId: 12418,
  rarity: 4,
  weapon: "claymore",
  statTable: MailedFlowerStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_mailed_flower",
      serializeId: 1,
      title: "talent_name.weapon_mailed_flower",
      description: "talent_descr.weapon_mailed_flower",
      refinementStats: [
        { atk_percent: 12, mastery: 48 }, // R1
        { atk_percent: 15, mastery: 60 }, // R2
        { atk_percent: 18, mastery: 72 }, // R3
        { atk_percent: 21, mastery: 84 }, // R4
        { atk_percent: 24, mastery: 96 }, // R5
      ],
    },
  ],
};
