// GENERATED by gen-armory.mjs — do not edit
/**
 * mappa_mare — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/MappaMare.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MappaMareStatTable } from "../generated/weaponStatTables.js";

export const mappaMare: DbObjectWeapon = {
  name: "mappa_mare",
  serializeId: 54,
  gameId: 14407,
  rarity: 4,
  weapon: "catalyst",
  statTable: MappaMareStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_mappa_mare",
      serializeId: 1,
      title: "talent_name.weapon_mappa_mare",
      description: "talent_descr.weapon_mappa_mare",
      maxStacks: 2,
      refinementStats: [
        { dmg_anemo: 8, dmg_geo: 8, dmg_pyro: 8, dmg_electro: 8, dmg_hydro: 8, dmg_cryo: 8, dmg_dendro: 8 }, // R1
        { dmg_anemo: 10, dmg_geo: 10, dmg_pyro: 10, dmg_electro: 10, dmg_hydro: 10, dmg_cryo: 10, dmg_dendro: 10 }, // R2
        { dmg_anemo: 12, dmg_geo: 12, dmg_pyro: 12, dmg_electro: 12, dmg_hydro: 12, dmg_cryo: 12, dmg_dendro: 12 }, // R3
        { dmg_anemo: 14, dmg_geo: 14, dmg_pyro: 14, dmg_electro: 14, dmg_hydro: 14, dmg_cryo: 14, dmg_dendro: 14 }, // R4
        { dmg_anemo: 16, dmg_geo: 16, dmg_pyro: 16, dmg_electro: 16, dmg_hydro: 16, dmg_cryo: 16, dmg_dendro: 16 }, // R5
      ],
    },
  ],
};
