// GENERATED by gen-armory.mjs — do not edit
/**
 * memory_of_dust — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/MemoryOfDust.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MemoryofDustStatTable } from "../generated/weaponStatTables.js";

export const memoryOfDust: DbObjectWeapon = {
  name: "memory_of_dust",
  serializeId: 48,
  gameId: 14504,
  rarity: 5,
  weapon: "catalyst",
  statTable: MemoryofDustStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_golden_majesty",
      description: "talent_descr.weapon_golden_majesty_passive",
      refinementStats: [
        { shield: 20 }, // R1
        { shield: 25 }, // R2
        { shield: 30 }, // R3
        { shield: 35 }, // R4
        { shield: 40 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_memory_of_dust",
      serializeId: 1,
      title: "talent_name.weapon_golden_majesty",
      description: "talent_descr.weapon_golden_majesty",
      maxStacks: 5,
      refinementStats: [
        { atk_percent: 8 }, // R1
        { atk_percent: 10 }, // R2
        { atk_percent: 12 }, // R3
        { atk_percent: 14 }, // R4
        { atk_percent: 16 }, // R5
      ],
    },
  ],
};
