// GENERATED by gen-armory.mjs — do not edit
/**
 * missive_windspear — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/MissiveWindspear.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MissiveWindspearStatTable } from "../generated/weaponStatTables.js";

export const missiveWindspear: DbObjectWeapon = {
  name: "missive_windspear",
  serializeId: 133,
  gameId: 13419,
  rarity: 4,
  weapon: "polearm",
  statTable: MissiveWindspearStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_missive_windspear",
      serializeId: 1,
      title: "talent_name.the_wind_unattained",
      description: "talent_descr.the_wind_unattained",
      refinementStats: [
        { atk_percent: 12, mastery: 48 }, // R1
        { atk_percent: 15, mastery: 60 }, // R2
        { atk_percent: 18, mastery: 72 }, // R3
        { atk_percent: 21, mastery: 84 }, // R4
        { atk_percent: 24, mastery: 96 }, // R5
      ],
    },
  ],
};
