// GENERATED by gen-armory.mjs — do not edit
/**
 * mitternachts_waltz — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/MitternachtsWaltz.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MitternachtsWaltzStatTable } from "../generated/weaponStatTables.js";

export const mitternachtsWaltz: DbObjectWeapon = {
  name: "mitternachts_waltz",
  serializeId: 98,
  gameId: 15412,
  rarity: 4,
  weapon: "bow",
  statTable: MitternachtsWaltzStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_mitternachts_waltz_1",
      serializeId: 1,
      title: "talent_name.weapon_mitternachts_waltz",
      description: "talent_descr.weapon_mitternachts_waltz_1",
      refinementStats: [
        { dmg_skill: 20 }, // R1
        { dmg_skill: 25 }, // R2
        { dmg_skill: 30 }, // R3
        { dmg_skill: 35 }, // R4
        { dmg_skill: 40 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_mitternachts_waltz_2",
      serializeId: 2,
      title: "talent_name.weapon_mitternachts_waltz",
      description: "talent_descr.weapon_mitternachts_waltz_2",
      refinementStats: [
        { dmg_normal: 20 }, // R1
        { dmg_normal: 25 }, // R2
        { dmg_normal: 30 }, // R3
        { dmg_normal: 35 }, // R4
        { dmg_normal: 40 }, // R5
      ],
    },
  ],
};
