// GENERATED by gen-armory.mjs — do not edit
/**
 * moonpiercer — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/Moonpiercer.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MoonpiercerStatTable } from "../generated/weaponStatTables.js";

export const moonpiercer: DbObjectWeapon = {
  name: "moonpiercer",
  serializeId: 128,
  gameId: 13417,
  rarity: 4,
  weapon: "polearm",
  statTable: MoonpiercerStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_stillwood_moonshadow",
      serializeId: 1,
      title: "talent_name.stillwood_moonshadow",
      description: "talent_descr.stillwood_moonshadow",
      refinementStats: [
        { atk_percent: 16 }, // R1
        { atk_percent: 20 }, // R2
        { atk_percent: 24 }, // R3
        { atk_percent: 28 }, // R4
        { atk_percent: 32 }, // R5
      ],
    },
  ],
};
