// GENERATED by gen-armory.mjs — do not edit
/**
 * morning_hibernation — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/MorningHibernation.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MorningHibernationStatTable } from "../generated/weaponStatTables.js";

export const morningHibernation: DbObjectWeapon = {
  name: "morning_hibernation",
  serializeId: 196,
  gameId: 14518,
  rarity: 5,
  weapon: "catalyst",
  statTable: MorningHibernationStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_morning_hibernation_1",
      serializeId: 1,
      title: "talent_name.weapon_morning_hibernation",
      description: "talent_descr.weapon_morning_hibernation_1",
      refinementStats: [
        { mastery: 120 }, // R1
        { mastery: 150 }, // R2
        { mastery: 180 }, // R3
        { mastery: 210 }, // R4
        { mastery: 240 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_morning_hibernation_2",
      serializeId: 2,
      title: "talent_name.weapon_morning_hibernation",
      description: "talent_descr.weapon_morning_hibernation_2",
      refinementStats: [
        { mastery: 96 }, // R1
        { mastery: 120 }, // R2
        { mastery: 144 }, // R3
        { mastery: 168 }, // R4
        { mastery: 192 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_morning_hibernation_3",
      serializeId: 3,
      title: "talent_name.weapon_morning_hibernation",
      description: "talent_descr.weapon_morning_hibernation_3",
      refinementStats: [
        { mastery: 32 }, // R1
        { mastery: 40 }, // R2
        { mastery: 48 }, // R3
        { mastery: 56 }, // R4
        { mastery: 64 }, // R5
      ],
    },
  ],
};
