// GENERATED by gen-armory.mjs — do not edit
/**
 * mountain_kings_fang — 5★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/MountainKingsFang.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MountainKingsFangStatTable } from "../generated/weaponStatTables.js";

export const mountainKingsFang: DbObjectWeapon = {
  name: "mountain_kings_fang",
  serializeId: 181,
  gameId: 12513,
  rarity: 5,
  weapon: "claymore",
  statTable: MountainKingsFangStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_mountain_kings_fang",
      serializeId: 1,
      title: "talent_name.weapon_mountain_kings_fang",
      description: "talent_descr.weapon_mountain_kings_fang",
      maxStacks: 6,
      refinementStats: [
        { dmg_skill: 10, dmg_burst: 10 }, // R1
        { dmg_skill: 12.5, dmg_burst: 12.5 }, // R2
        { dmg_skill: 15, dmg_burst: 15 }, // R3
        { dmg_skill: 17.5, dmg_burst: 17.5 }, // R4
        { dmg_skill: 20, dmg_burst: 20 }, // R5
      ],
    },
  ],
};
