// GENERATED by gen-armory.mjs — do not edit
/**
 * mountain_bracing_bolt — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/MountainBracingBolt.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MountainBracingBoltStatTable } from "../generated/weaponStatTables.js";

export const mountainBracingBolt: DbObjectWeapon = {
  name: "mountain_bracing_bolt",
  serializeId: 187,
  gameId: 13430,
  rarity: 4,
  weapon: "polearm",
  statTable: MountainBracingBoltStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_mountain_bracing_bolt",
      description: "talent_descr.weapon_mountain_bracing_bolt_1",
      refinementStats: [
        { dmg_skill: 12 }, // R1
        { dmg_skill: 15 }, // R2
        { dmg_skill: 18 }, // R3
        { dmg_skill: 21 }, // R4
        { dmg_skill: 24 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_mountain_bracing_bolt",
      serializeId: 1,
      title: "talent_name.weapon_mountain_bracing_bolt",
      description: "talent_descr.weapon_mountain_bracing_bolt_2",
      refinementStats: [
        { dmg_skill: 12 }, // R1
        { dmg_skill: 15 }, // R2
        { dmg_skill: 18 }, // R3
        { dmg_skill: 21 }, // R4
        { dmg_skill: 24 }, // R5
      ],
    },
  ],
};
