// GENERATED by gen-armory.mjs — do not edit
/**
 * oathsworn_eye — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/OathswornEye.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { OathswornEyeStatTable } from "../generated/weaponStatTables.js";

export const oathswornEye: DbObjectWeapon = {
  name: "oathsworn_eye",
  serializeId: 120,
  gameId: 14415,
  rarity: 4,
  weapon: "catalyst",
  statTable: OathswornEyeStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_oathsworn_eye",
      serializeId: 1,
      title: "talent_name.weapon_oathsworn_eye",
      description: "talent_descr.weapon_oathsworn_eye",
      refinementStats: [
        { recharge: 24 }, // R1
        { recharge: 30 }, // R2
        { recharge: 36 }, // R3
        { recharge: 42 }, // R4
        { recharge: 48 }, // R5
      ],
    },
  ],
};
