// GENERATED by gen-armory.mjs — do not edit
/**
 * otherworldly_story — 3★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/OtherworldlyStory.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { OtherworldlyStoryStatTable } from "../generated/weaponStatTables.js";

export const otherworldlyStory: DbObjectWeapon = {
  name: "otherworldly_story",
  serializeId: 59,
  gameId: 14303,
  rarity: 3,
  weapon: "catalyst",
  statTable: OtherworldlyStoryStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_otherworldly_story",
      description: "talent_descr.weapon_otherworldly_story",
      refinementStats: [

      ],
    },
  ],
};
