// GENERATED by gen-armory.mjs — do not edit
/**
 * portable_power_saw — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/PortablePowerSaw.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { PortablePowerSawStatTable } from "../generated/weaponStatTables.js";

export const portablePowerSaw: DbObjectWeapon = {
  name: "portable_power_saw",
  serializeId: 159,
  gameId: 12427,
  rarity: 4,
  weapon: "claymore",
  statTable: PortablePowerSawStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_sea_shanty",
      serializeId: 1,
      title: "talent_name.weapon_sea_shanty",
      description: "talent_descr.weapon_sea_shanty",
      maxStacks: 3,
      refinementStats: [
        { mastery: 40 }, // R1
        { mastery: 50 }, // R2
        { mastery: 60 }, // R3
        { mastery: 70 }, // R4
        { mastery: 80 }, // R5
      ],
    },
  ],
};
