// GENERATED by gen-armory.mjs — do not edit
/**
 * primordial_jade_winged_spear — 5★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/PrimordialJadeWingedSpear.js
 *
 * Passive: White Jade Whisker
 *   - ConditionStacks (name: "primordial_jade_winged_spear", maxStacks: 7):
 *       Per-stack ATK% at R1..R5: [3.2, 3.9, 4.6, 5.3, 6]
 *       (raw also carries text_percent display stat — omitted as display-only)
 *   - ConditionBooleanValue (setting: "primordial_jade_winged_spear", cond: ge, value: 7):
 *       At max stacks (7), grant dmg_all: [12, 15, 18, 21, 24] at R1..R5
 *
 * Oracle passiveToggles: { primordial_jade_winged_spear: 7 } (max stacks → both conditions active)
 */

import type { DbObjectWeapon } from "@genshin/types";
import { PrimordialJadeWingedSpearStatTable } from "../generated/weaponStatTables.js";

export const primordialJadeWingedSpear: DbObjectWeapon = {
  name: "primordial_jade_winged_spear",
  serializeId: 94,
  gameId: 13505,
  rarity: 5,
  weapon: "polearm",
  statTable: PrimordialJadeWingedSpearStatTable,
  conditions: [
    {
      type: "stacks",
      name: "primordial_jade_winged_spear",
      serializeId: 1,
      title: "talent_name.primordial_jade_winged_spear",
      description: "talent_descr.primordial_jade_winged_spear_1",
      maxStacks: 7,
      refinementStats: [
        { atk_percent: 3.2 }, // R1
        { atk_percent: 3.9 }, // R2
        { atk_percent: 4.6 }, // R3
        { atk_percent: 5.3 }, // R4
        { atk_percent: 6 },   // R5
      ],
    },
    {
      type: "boolean-value",
      title: "talent_name.primordial_jade_winged_spear",
      description: "talent_descr.primordial_jade_winged_spear_2",
      setting: "primordial_jade_winged_spear",
      cond: "ge",
      value: 7,
      refinementStats: [
        { dmg_all: 12 }, // R1
        { dmg_all: 15 }, // R2
        { dmg_all: 18 }, // R3
        { dmg_all: 21 }, // R4
        { dmg_all: 24 }, // R5
      ],
    },
  ],
};
