// GENERATED by gen-armory.mjs — do not edit
/**
 * prototype_rancour — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/PrototypeRancour.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { PrototypeRancourStatTable } from "../generated/weaponStatTables.js";

export const prototypeRancour: DbObjectWeapon = {
  name: "prototype_rancour",
  serializeId: 15,
  gameId: 11406,
  rarity: 4,
  weapon: "sword",
  statTable: PrototypeRancourStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_prototype_rancour",
      serializeId: 1,
      title: "talent_name.weapon_prototype_rancour",
      description: "talent_descr.weapon_prototype_rancour",
      maxStacks: 4,
      refinementStats: [
        { atk_percent: 4, def_percent: 4 }, // R1
        { atk_percent: 5, def_percent: 5 }, // R2
        { atk_percent: 6, def_percent: 6 }, // R3
        { atk_percent: 7, def_percent: 7 }, // R4
        { atk_percent: 8, def_percent: 8 }, // R5
      ],
    },
  ],
};
