// GENERATED by gen-armory.mjs — do not edit
/**
 * prototype_amber — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/PrototypeAmber.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { PrototypeAmberStatTable } from "../generated/weaponStatTables.js";

export const prototypeAmber: DbObjectWeapon = {
  name: "prototype_amber",
  serializeId: 53,
  gameId: 14406,
  rarity: 4,
  weapon: "catalyst",
  statTable: PrototypeAmberStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_prototype_amber",
      description: "talent_descr.weapon_prototype_amber",
      refinementStats: [

      ],
    },
  ],
};
