// GENERATED by gen-armory.mjs — do not edit
/**
 * prototype_starglitter — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/PrototypeStarglitter.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { PrototypeStarglitterStatTable } from "../generated/weaponStatTables.js";

export const prototypeStarglitter: DbObjectWeapon = {
  name: "prototype_starglitter",
  serializeId: 89,
  gameId: 13402,
  rarity: 4,
  weapon: "polearm",
  statTable: PrototypeStarglitterStatTable,
  conditions: [
    {
      type: "stacks",
      name: "prototype_starglitter",
      serializeId: 1,
      title: "talent_name.prototype_starglitter",
      description: "talent_descr.prototype_starglitter",
      maxStacks: 2,
      refinementStats: [
        { dmg_normal: 8, dmg_charged: 8 }, // R1
        { dmg_normal: 10, dmg_charged: 10 }, // R2
        { dmg_normal: 12, dmg_charged: 12 }, // R3
        { dmg_normal: 14, dmg_charged: 14 }, // R4
        { dmg_normal: 16, dmg_charged: 16 }, // R5
      ],
    },
  ],
};
