// GENERATED by gen-armory.mjs — do not edit
/**
 * prototype_crescent — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/PrototypeCrescent.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { PrototypeCrescentStatTable } from "../generated/weaponStatTables.js";

export const prototypeCrescent: DbObjectWeapon = {
  name: "prototype_crescent",
  serializeId: 30,
  gameId: 15406,
  rarity: 4,
  weapon: "bow",
  statTable: PrototypeCrescentStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_prototype_crescent",
      serializeId: 1,
      title: "talent_name.weapon_prototype_crescent",
      description: "talent_descr.weapon_prototype_crescent",
      refinementStats: [
        { atk_percent: 36, move_speed: 10 }, // R1
        { atk_percent: 45, move_speed: 10 }, // R2
        { atk_percent: 54, move_speed: 10 }, // R3
        { atk_percent: 63, move_speed: 10 }, // R4
        { atk_percent: 72, move_speed: 10 }, // R5
      ],
    },
  ],
};
