// GENERATED by gen-armory.mjs — do not edit
/**
 * rainbows_trail — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/RainbowsTrail.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { RainbowsTrailStatTable } from "../generated/weaponStatTables.js";

export const rainbowsTrail: DbObjectWeapon = {
  name: "rainbows_trail",
  serializeId: 183,
  gameId: 13431,
  rarity: 4,
  weapon: "polearm",
  statTable: RainbowsTrailStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_rainbows_trail",
      serializeId: 1,
      title: "talent_name.weapon_rainbows_trail",
      description: "talent_descr.weapon_rainbows_trail",
      refinementStats: [
        { def_percent: 16 }, // R1
        { def_percent: 20 }, // R2
        { def_percent: 24 }, // R3
        { def_percent: 28 }, // R4
        { def_percent: 32 }, // R5
      ],
    },
  ],
};
