// GENERATED by gen-armory.mjs — do not edit
/**
 * range_gauge — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/RangeGauge.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { RangeGaugeStatTable } from "../generated/weaponStatTables.js";

export const rangeGauge: DbObjectWeapon = {
  name: "range_gauge",
  serializeId: 161,
  gameId: 15427,
  rarity: 4,
  weapon: "bow",
  statTable: RangeGaugeStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_masons_ditty",
      serializeId: 1,
      title: "talent_name.weapon_masons_ditty",
      description: "talent_descr.weapon_masons_ditty",
      maxStacks: 3,
      refinementStats: [
        { atk_percent: 3, dmg_anemo: 7, dmg_geo: 7, dmg_pyro: 7, dmg_electro: 7, dmg_hydro: 7, dmg_cryo: 7, dmg_dendro: 7 }, // R1
        { atk_percent: 4, dmg_anemo: 8.5, dmg_geo: 8.5, dmg_pyro: 8.5, dmg_electro: 8.5, dmg_hydro: 8.5, dmg_cryo: 8.5, dmg_dendro: 8.5 }, // R2
        { atk_percent: 5, dmg_anemo: 10, dmg_geo: 10, dmg_pyro: 10, dmg_electro: 10, dmg_hydro: 10, dmg_cryo: 10, dmg_dendro: 10 }, // R3
        { atk_percent: 6, dmg_anemo: 11.5, dmg_geo: 11.5, dmg_pyro: 11.5, dmg_electro: 11.5, dmg_hydro: 11.5, dmg_cryo: 11.5, dmg_dendro: 11.5 }, // R4
        { atk_percent: 7, dmg_anemo: 13, dmg_geo: 13, dmg_pyro: 13, dmg_electro: 13, dmg_hydro: 13, dmg_cryo: 13, dmg_dendro: 13 }, // R5
      ],
    },
  ],
};
