// GENERATED by gen-armory.mjs — do not edit
/**
 * recurve_bow — 3★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/RecurveBow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { RecurveBowStatTable } from "../generated/weaponStatTables.js";

export const recurveBow: DbObjectWeapon = {
  name: "recurve_bow",
  serializeId: 32,
  gameId: 15303,
  rarity: 3,
  weapon: "bow",
  statTable: RecurveBowStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_cull_the_weal",
      description: "talent_descr.weapon_cull_the_weal",
      refinementStats: [

      ],
    },
  ],
};
