// GENERATED by gen-armory.mjs — do not edit
/**
 * rightful_reward — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/RightfulReward.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { RightfulRewardStatTable } from "../generated/weaponStatTables.js";

export const rightfulReward: DbObjectWeapon = {
  name: "rightful_reward",
  serializeId: 152,
  gameId: 13425,
  rarity: 4,
  weapon: "polearm",
  statTable: RightfulRewardStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_rightful_reward",
      description: "talent_descr.weapon_rightful_reward",
      refinementStats: [

      ],
    },
  ],
};
