// GENERATED by gen-armory.mjs — do not edit
/**
 * royal_bow — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/RoyalBow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { RoyalBowStatTable } from "../generated/weaponStatTables.js";

export const royalBow: DbObjectWeapon = {
  name: "royal_bow",
  serializeId: 33,
  gameId: 15404,
  rarity: 4,
  weapon: "bow",
  statTable: RoyalBowStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_royal_bow",
      serializeId: 1,
      title: "talent_name.weapon_focus",
      description: "talent_descr.weapon_focus",
      maxStacks: 5,
      refinementStats: [
        { crit_rate: 8 }, // R1
        { crit_rate: 10 }, // R2
        { crit_rate: 12 }, // R3
        { crit_rate: 14 }, // R4
        { crit_rate: 16 }, // R5
      ],
      condition: {
        type: "boolean",
        name: "weapon_royal_avg_crit_rate",
        invert: true,
      },
    },
    {
      type: "boolean-refine",
      name: "weapon_royal_avg_crit_rate",
      serializeId: 2,
      title: "talent_name.weapon_royal_avg_crit_rate",
      description: "talent_descr.weapon_royal_avg_crit_rate",
      refinementStats: [
        { royal_crit_rate: 8 }, // R1
        { royal_crit_rate: 10 }, // R2
        { royal_crit_rate: 12 }, // R3
        { royal_crit_rate: 14 }, // R4
        { royal_crit_rate: 16 }, // R5
      ],
    },
  ],
};
