// GENERATED by gen-armory.mjs — do not edit
/**
 * royal_longsword — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/RoyalLongsword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { RoyalLongswordStatTable } from "../generated/weaponStatTables.js";

export const royalLongsword: DbObjectWeapon = {
  name: "royal_longsword",
  serializeId: 16,
  gameId: 11404,
  rarity: 4,
  weapon: "sword",
  statTable: RoyalLongswordStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_royal_longsword",
      serializeId: 1,
      title: "talent_name.weapon_focus",
      description: "talent_descr.weapon_focus",
      maxStacks: 5,
      refinementStats: [
        { crit_rate: 8 }, // R1
        { crit_rate: 10 }, // R2
        { crit_rate: 12 }, // R3
        { crit_rate: 14 }, // R4
        { crit_rate: 16 }, // R5
      ],
      condition: {
        type: "boolean",
        name: "weapon_royal_avg_crit_rate",
        invert: true,
      },
    },
    {
      type: "boolean-refine",
      name: "weapon_royal_avg_crit_rate",
      serializeId: 2,
      title: "talent_name.weapon_royal_avg_crit_rate",
      description: "talent_descr.weapon_royal_avg_crit_rate",
      refinementStats: [
        { royal_crit_rate: 8 }, // R1
        { royal_crit_rate: 10 }, // R2
        { royal_crit_rate: 12 }, // R3
        { royal_crit_rate: 14 }, // R4
        { royal_crit_rate: 16 }, // R5
      ],
    },
  ],
};
