// GENERATED by gen-armory.mjs — do not edit
/**
 * rust — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/Rust.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { RustStatTable } from "../generated/weaponStatTables.js";

export const rust: DbObjectWeapon = {
  name: "rust",
  serializeId: 34,
  gameId: 15405,
  rarity: 4,
  weapon: "bow",
  statTable: RustStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_rust_passive",
      description: "talent_descr.weapon_rust_passive",
      refinementStats: [
        { dmg_normal: 40, dmg_charged: -10 }, // R1
        { dmg_normal: 50, dmg_charged: -10 }, // R2
        { dmg_normal: 60, dmg_charged: -10 }, // R3
        { dmg_normal: 70, dmg_charged: -10 }, // R4
        { dmg_normal: 80, dmg_charged: -10 }, // R5
      ],
    },
  ],
};
