// GENERATED by gen-armory.mjs — do not edit
/**
 * sacrificial_fragments — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/SacrificialFragments.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SacrificialFragmentsStatTable } from "../generated/weaponStatTables.js";

export const sacrificialFragments: DbObjectWeapon = {
  name: "sacrificial_fragments",
  serializeId: 51,
  gameId: 14403,
  rarity: 4,
  weapon: "catalyst",
  statTable: SacrificialFragmentsStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_sacrificial_passive",
      description: "talent_descr.weapon_sacrificial_passive",
      refinementStats: [

      ],
    },
  ],
};
