// GENERATED by gen-armory.mjs — do not edit
/**
 * sacrificial_greatsword — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/SacrificialGreatsword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SacrificialGreatswordStatTable } from "../generated/weaponStatTables.js";

export const sacrificialGreatsword: DbObjectWeapon = {
  name: "sacrificial_greatsword",
  serializeId: 73,
  gameId: 12403,
  rarity: 4,
  weapon: "claymore",
  statTable: SacrificialGreatswordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_sacrificial_passive",
      description: "talent_descr.weapon_sacrificial_passive",
      refinementStats: [

      ],
    },
  ],
};
