// GENERATED by gen-armory.mjs — do not edit
/**
 * sacrificial_sword — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/SacrificialSword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SacrificialSwordStatTable } from "../generated/weaponStatTables.js";

export const sacrificialSword: DbObjectWeapon = {
  name: "sacrificial_sword",
  serializeId: 17,
  gameId: 11403,
  rarity: 4,
  weapon: "sword",
  statTable: SacrificialSwordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_sacrificial_passive",
      description: "talent_descr.weapon_sacrificial_passive",
      refinementStats: [

      ],
    },
  ],
};
