// GENERATED by gen-armory.mjs — do not edit
/**
 * sacrificial_bow — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/SacrificialBow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SacrificialBowStatTable } from "../generated/weaponStatTables.js";

export const sacrificialBow: DbObjectWeapon = {
  name: "sacrificial_bow",
  serializeId: 35,
  gameId: 15403,
  rarity: 4,
  weapon: "bow",
  statTable: SacrificialBowStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_sacrificial_passive",
      description: "talent_descr.weapon_sacrificial_passive",
      refinementStats: [

      ],
    },
  ],
};
