// GENERATED by gen-armory.mjs — do not edit
/**
 * sacrificial_jade — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/SacrificialJade.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SacrificialJadeStatTable } from "../generated/weaponStatTables.js";

export const sacrificialJade: DbObjectWeapon = {
  name: "sacrificial_jade",
  serializeId: 153,
  gameId: 14424,
  rarity: 4,
  weapon: "catalyst",
  statTable: SacrificialJadeStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_sacrificial_jade",
      serializeId: 1,
      title: "talent_name.weapon_sacrificial_jade",
      description: "talent_descr.weapon_sacrificial_jade",
      refinementStats: [
        { hp_percent: 32, mastery: 40 }, // R1
        { hp_percent: 40, mastery: 50 }, // R2
        { hp_percent: 48, mastery: 60 }, // R3
        { hp_percent: 56, mastery: 70 }, // R4
        { hp_percent: 64, mastery: 80 }, // R5
      ],
    },
  ],
};
