// GENERATED by gen-armory.mjs — do not edit
/**
 * sapwood_blade — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/SapwoodBlade.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SapwoodBladeStatTable } from "../generated/weaponStatTables.js";

export const sapwoodBlade: DbObjectWeapon = {
  name: "sapwood_blade",
  serializeId: 126,
  gameId: 11417,
  rarity: 4,
  weapon: "sword",
  statTable: SapwoodBladeStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_forest_sanctuary",
      serializeId: 1,
      title: "talent_name.forest_sanctuary",
      description: "talent_descr.forest_sanctuary",
      refinementStats: [
        { mastery: 60 }, // R1
        { mastery: 75 }, // R2
        { mastery: 90 }, // R3
        { mastery: 105 }, // R4
        { mastery: 120 }, // R5
      ],
    },
  ],
};
