// GENERATED by gen-armory.mjs — do not edit
/**
 * serpent_spine — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/SerpentSpine.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SerpentSpineStatTable } from "../generated/weaponStatTables.js";

export const serpentSpine: DbObjectWeapon = {
  name: "serpent_spine",
  serializeId: 42,
  gameId: 12409,
  rarity: 4,
  weapon: "claymore",
  statTable: SerpentSpineStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_serpent_spine",
      serializeId: 1,
      title: "talent_name.weapon_wavesplitter",
      description: "talent_descr.weapon_wavesplitter",
      maxStacks: 5,
      refinementStats: [
        { dmg_all: 6, dmg_recieved: 3 }, // R1
        { dmg_all: 7, dmg_recieved: 2.7 }, // R2
        { dmg_all: 8, dmg_recieved: 2.4 }, // R3
        { dmg_all: 9, dmg_recieved: 2.2 }, // R4
        { dmg_all: 10, dmg_recieved: 2 }, // R5
      ],
    },
  ],
};
