// GENERATED by gen-armory.mjs — do not edit
/**
 * sharpshooters_oath — 3★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/SharpshooterOath.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SharpshootersOathStatTable } from "../generated/weaponStatTables.js";

export const sharpshootersOath: DbObjectWeapon = {
  name: "sharpshooters_oath",
  serializeId: 36,
  gameId: 15302,
  rarity: 3,
  weapon: "bow",
  statTable: SharpshootersOathStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_sharpshooter_oath",
      description: "talent_descr.weapon_sharpshooter_oath",
      refinementStats: [
        { dmg_weak: 24 }, // R1
        { dmg_weak: 30 }, // R2
        { dmg_weak: 36 }, // R3
        { dmg_weak: 42 }, // R4
        { dmg_weak: 48 }, // R5
      ],
    },
  ],
};
