// GENERATED by gen-armory.mjs — do not edit
/**
 * skyrider_sword — 3★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/SkyriderSword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SkyriderSwordStatTable } from "../generated/weaponStatTables.js";

export const skyriderSword: DbObjectWeapon = {
  name: "skyrider_sword",
  serializeId: 18,
  gameId: 11306,
  rarity: 3,
  weapon: "sword",
  statTable: SkyriderSwordStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_skyrider_sword",
      serializeId: 1,
      title: "talent_name.weapon_skyrider_sword",
      description: "talent_descr.weapon_skyrider_sword",
      refinementStats: [
        { atk_percent: 12, move_speed: 12 }, // R1
        { atk_percent: 15, move_speed: 15 }, // R2
        { atk_percent: 18, move_speed: 18 }, // R3
        { atk_percent: 21, move_speed: 21 }, // R4
        { atk_percent: 24, move_speed: 24 }, // R5
      ],
    },
  ],
};
