// GENERATED by gen-armory.mjs — do not edit
/**
 * skyrider_greatsword — 3★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/SkyriderGreatsword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SkyriderGreatswordStatTable } from "../generated/weaponStatTables.js";

export const skyriderGreatsword: DbObjectWeapon = {
  name: "skyrider_greatsword",
  serializeId: 78,
  gameId: 12306,
  rarity: 3,
  weapon: "claymore",
  statTable: SkyriderGreatswordStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_skyrider_greatsword",
      serializeId: 1,
      title: "talent_name.weapon_courage",
      description: "talent_descr.weapon_courage",
      maxStacks: 4,
      refinementStats: [
        { atk_percent: 6 }, // R1
        { atk_percent: 7 }, // R2
        { atk_percent: 8 }, // R3
        { atk_percent: 9 }, // R4
        { atk_percent: 10 }, // R5
      ],
    },
  ],
};
