// GENERATED by gen-armory.mjs — do not edit
/**
 * song_of_stillness — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/SongOfStillness.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SongOfStillnessStatTable } from "../generated/weaponStatTables.js";

export const songOfStillness: DbObjectWeapon = {
  name: "song_of_stillness",
  serializeId: 156,
  gameId: 15425,
  rarity: 4,
  weapon: "bow",
  statTable: SongOfStillnessStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_song_of_stillness",
      serializeId: 1,
      title: "talent_name.weapon_song_of_stillness",
      description: "talent_descr.weapon_song_of_stillness",
      refinementStats: [
        { dmg_all: 16 }, // R1
        { dmg_all: 20 }, // R2
        { dmg_all: 24 }, // R3
        { dmg_all: 28 }, // R4
        { dmg_all: 32 }, // R5
      ],
    },
  ],
};
