// GENERATED by gen-armory.mjs — do not edit
/**
 * splendor_of_tranquil_waters — 5★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/SplendorOfStillWaters.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SplendorOfStillWatersStatTable } from "../generated/weaponStatTables.js";

export const splendorOfTranquilWaters: DbObjectWeapon = {
  name: "splendor_of_tranquil_waters",
  serializeId: 165,
  gameId: 11513,
  rarity: 5,
  weapon: "sword",
  statTable: SplendorOfStillWatersStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_splendor_of_tranquil_waters",
      serializeId: 1,
      title: "talent_name.weapon_splendor_of_tranquil_waters",
      description: "talent_descr.weapon_splendor_of_tranquil_waters_1",
      maxStacks: 3,
      refinementStats: [
        { dmg_skill: 8 }, // R1
        { dmg_skill: 10 }, // R2
        { dmg_skill: 12 }, // R3
        { dmg_skill: 14 }, // R4
        { dmg_skill: 16 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_splendor_of_tranquil_waters_2",
      serializeId: 2,
      title: "talent_name.weapon_splendor_of_tranquil_waters",
      description: "talent_descr.weapon_splendor_of_tranquil_waters_2",
      maxStacks: 2,
      refinementStats: [
        { hp_percent: 14 }, // R1
        { hp_percent: 16 }, // R2
        { hp_percent: 20 }, // R3
        { hp_percent: 24 }, // R4
        { hp_percent: 28 }, // R5
      ],
    },
  ],
};
