// GENERATED by gen-armory.mjs — do not edit
/**
 * starcallers_watch — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/StarcallersWatch.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { StarcallersWatchStatTable } from "../generated/weaponStatTables.js";

export const starcallersWatch: DbObjectWeapon = {
  name: "starcallers_watch",
  serializeId: 195,
  gameId: 14517,
  rarity: 5,
  weapon: "catalyst",
  statTable: StarcallersWatchStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_starcallers_watch",
      description: "talent_descr.weapon_starcallers_watch_1",
      refinementStats: [
        { mastery: 100 }, // R1
        { mastery: 125 }, // R2
        { mastery: 150 }, // R3
        { mastery: 175 }, // R4
        { mastery: 200 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_starcallers_watch",
      serializeId: 1,
      title: "talent_name.weapon_starcallers_watch",
      description: "talent_descr.weapon_starcallers_watch_2",
      refinementStats: [
        { dmg_all: 28 }, // R1
        { dmg_all: 35 }, // R2
        { dmg_all: 42 }, // R3
        { dmg_all: 49 }, // R4
        { dmg_all: 56 }, // R5
      ],
    },
  ],
};
