// GENERATED by gen-armory.mjs — do not edit
/**
 * surfing_time — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/SurfingTime.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SurfingTimeStatTable } from "../generated/weaponStatTables.js";

export const surfingTime: DbObjectWeapon = {
  name: "surfing_time",
  serializeId: 178,
  gameId: 14516,
  rarity: 5,
  weapon: "catalyst",
  statTable: SurfingTimeStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_surfing_time",
      description: "talent_descr.weapon_surfing_time_1",
      refinementStats: [
        { hp_percent: 20 }, // R1
        { hp_percent: 25 }, // R2
        { hp_percent: 30 }, // R3
        { hp_percent: 35 }, // R4
        { hp_percent: 40 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_surfing_time",
      serializeId: 1,
      title: "talent_name.weapon_surfing_time",
      description: "talent_descr.weapon_surfing_time_2",
      maxStacks: 4,
      refinementStats: [
        { dmg_normal: 12 }, // R1
        { dmg_normal: 15 }, // R2
        { dmg_normal: 18 }, // R3
        { dmg_normal: 21 }, // R4
        { dmg_normal: 24 }, // R5
      ],
    },
  ],
};
