// GENERATED by gen-armory.mjs — do not edit
/**
 * symphonist_of_scents — 5★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/SymphonistofScents.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { SymphonistofScentsStatTable } from "../generated/weaponStatTables.js";

export const symphonistOfScents: DbObjectWeapon = {
  name: "symphonist_of_scents",
  serializeId: 199,
  gameId: 13514,
  rarity: 5,
  weapon: "polearm",
  statTable: SymphonistofScentsStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_symphonist_of_scents",
      description: "talent_descr.weapon_symphonist_of_scents_1",
      refinementStats: [
        { atk_percent: 12 }, // R1
        { atk_percent: 15 }, // R2
        { atk_percent: 18 }, // R3
        { atk_percent: 21 }, // R4
        { atk_percent: 24 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "symphonist_of_scents_2",
      serializeId: 1,
      title: "talent_name.weapon_symphonist_of_scents",
      description: "talent_descr.weapon_symphonist_of_scents_2",
      refinementStats: [
        { atk_percent: 12 }, // R1
        { atk_percent: 15 }, // R2
        { atk_percent: 18 }, // R3
        { atk_percent: 21 }, // R4
        { atk_percent: 24 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "symphonist_of_scents_3",
      serializeId: 2,
      title: "talent_name.weapon_symphonist_of_scents",
      description: "talent_descr.weapon_symphonist_of_scents_3",
      refinementStats: [
        { atk_percent: 32 }, // R1
        { atk_percent: 40 }, // R2
        { atk_percent: 48 }, // R3
        { atk_percent: 56 }, // R4
        { atk_percent: 64 }, // R5
      ],
    },
  ],
};
