// GENERATED by gen-armory.mjs — do not edit
/**
 * talking_stick — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/TalkingStick.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { TalkingStickStatTable } from "../generated/weaponStatTables.js";

export const talkingStick: DbObjectWeapon = {
  name: "talking_stick",
  serializeId: 149,
  gameId: 12424,
  rarity: 4,
  weapon: "claymore",
  statTable: TalkingStickStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_talking_stick_1",
      serializeId: 1,
      title: "talent_name.weapon_talking_stick_1",
      description: "talent_descr.weapon_talking_stick_1",
      refinementStats: [
        { atk_percent: 16 }, // R1
        { atk_percent: 20 }, // R2
        { atk_percent: 24 }, // R3
        { atk_percent: 28 }, // R4
        { atk_percent: 32 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_talking_stick_2",
      serializeId: 2,
      title: "talent_name.weapon_talking_stick_2",
      description: "talent_descr.weapon_talking_stick_2",
      refinementStats: [
        { dmg_anemo: 12, dmg_geo: 12, dmg_pyro: 12, dmg_electro: 12, dmg_hydro: 12, dmg_cryo: 12, dmg_dendro: 12 }, // R1
        { dmg_anemo: 15, dmg_geo: 15, dmg_pyro: 15, dmg_electro: 15, dmg_hydro: 15, dmg_cryo: 15, dmg_dendro: 15 }, // R2
        { dmg_anemo: 18, dmg_geo: 18, dmg_pyro: 18, dmg_electro: 18, dmg_hydro: 18, dmg_cryo: 18, dmg_dendro: 18 }, // R3
        { dmg_anemo: 21, dmg_geo: 21, dmg_pyro: 21, dmg_electro: 21, dmg_hydro: 21, dmg_cryo: 21, dmg_dendro: 21 }, // R4
        { dmg_anemo: 24, dmg_geo: 24, dmg_pyro: 24, dmg_electro: 24, dmg_hydro: 24, dmg_cryo: 24, dmg_dendro: 24 }, // R5
      ],
    },
  ],
};
