// GENERATED by gen-armory.mjs — do not edit
/**
 * the_stringless — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/Stringless.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { StringlessStatTable } from "../generated/weaponStatTables.js";

export const theStringless: DbObjectWeapon = {
  name: "the_stringless",
  serializeId: 39,
  gameId: 15402,
  rarity: 4,
  weapon: "bow",
  statTable: StringlessStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_stringless",
      description: "talent_descr.weapon_stringless",
      refinementStats: [
        { dmg_burst: 24, dmg_skill: 24 }, // R1
        { dmg_burst: 30, dmg_skill: 30 }, // R2
        { dmg_burst: 36, dmg_skill: 36 }, // R3
        { dmg_burst: 42, dmg_skill: 42 }, // R4
        { dmg_burst: 48, dmg_skill: 48 }, // R5
      ],
    },
  ],
};
