// GENERATED by gen-armory.mjs — do not edit
/**
 * the_black_sword — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/BlackSword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { BlackSwordStatTable } from "../generated/weaponStatTables.js";

export const theBlackSword: DbObjectWeapon = {
  name: "the_black_sword",
  serializeId: 4,
  gameId: 11409,
  rarity: 4,
  weapon: "sword",
  statTable: BlackSwordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_black_sword",
      description: "talent_descr.weapon_black_sword",
      refinementStats: [
        { dmg_normal: 20, dmg_charged: 20 }, // R1
        { dmg_normal: 25, dmg_charged: 25 }, // R2
        { dmg_normal: 30, dmg_charged: 30 }, // R3
        { dmg_normal: 35, dmg_charged: 35 }, // R4
        { dmg_normal: 40, dmg_charged: 40 }, // R5
      ],
    },
  ],
};
