// GENERATED by gen-armory.mjs — do not edit
/**
 * the_dockhands_assistant — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/TheDockhandsAssistant.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { TheDockhandsAssistantStatTable } from "../generated/weaponStatTables.js";

export const theDockhandsAssistant: DbObjectWeapon = {
  name: "the_dockhands_assistant",
  serializeId: 158,
  gameId: 11427,
  rarity: 4,
  weapon: "sword",
  statTable: TheDockhandsAssistantStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_sea_shanty",
      serializeId: 1,
      title: "talent_name.weapon_sea_shanty",
      description: "talent_descr.weapon_sea_shanty",
      maxStacks: 3,
      refinementStats: [
        { mastery: 40 }, // R1
        { mastery: 50 }, // R2
        { mastery: 60 }, // R3
        { mastery: 70 }, // R4
        { mastery: 80 }, // R5
      ],
    },
  ],
};
