// GENERATED by gen-armory.mjs — do not edit
/**
 * thrilling_tales_of_dragon_slayers — 3★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/ThrillingTales.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { ThrillingTalesofDragonSlayersStatTable } from "../generated/weaponStatTables.js";

export const thrillingTalesOfDragonSlayers: DbObjectWeapon = {
  name: "thrilling_tales_of_dragon_slayers",
  serializeId: 58,
  gameId: 14302,
  rarity: 3,
  weapon: "catalyst",
  statTable: ThrillingTalesofDragonSlayersStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_thrilling_tales",
      description: "talent_descr.weapon_thrilling_tales",
      refinementStats: [

      ],
    },
  ],
};
