// GENERATED by gen-armory.mjs — do not edit
/**
 * tidal_shadow — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/TidalShadow.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { TidalShadowStatTable } from "../generated/weaponStatTables.js";

export const tidalShadow: DbObjectWeapon = {
  name: "tidal_shadow",
  serializeId: 150,
  gameId: 12425,
  rarity: 4,
  weapon: "claymore",
  statTable: TidalShadowStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_tidal_shadow",
      serializeId: 1,
      title: "talent_name.weapon_tidal_shadow",
      description: "talent_descr.weapon_tidal_shadow",
      refinementStats: [
        { atk_percent: 24 }, // R1
        { atk_percent: 30 }, // R2
        { atk_percent: 36 }, // R3
        { atk_percent: 42 }, // R4
        { atk_percent: 48 }, // R5
      ],
    },
  ],
};
