// GENERATED by gen-armory.mjs — do not edit
/**
 * tome_of_the_eternal_flow — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/TomeoftheEternalFlow.js
 *
 * Passive: Carry On
 *   - ConditionStaticRefine (always-on):
 *       HP% at R1..R5: [16, 20, 24, 28, 32]
 *   - ConditionStacks (name: "weapon_tome_of_the_eternal_flow", maxStacks: 3):
 *       Per-stack dmg_charged at R1..R5: [14, 18, 22, 26, 30]
 *   - ConditionStaticRefine gated by ConditionBooleanValue (setting:
 *       "weapon_tome_of_the_eternal_flow", cond: ge, value: 3) only carries
 *       text_value (display-only) — OMITTED (no damage contribution).
 *
 * Oracle passiveToggles: { weapon_tome_of_the_eternal_flow: 3 } (max stacks active)
 * Real damage = StaticRefine hp% + Stacks × dmg_charged
 */

import type { DbObjectWeapon } from "@genshin/types";
import { TomeoftheEternalFlowStatTable } from "../generated/weaponStatTables.js";

export const tomeOfTheEternalFlow: DbObjectWeapon = {
  name: "tome_of_the_eternal_flow",
  serializeId: 164,
  gameId: 14514,
  rarity: 5,
  weapon: "catalyst",
  statTable: TomeoftheEternalFlowStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_tome_of_the_eternal_flow",
      description: "talent_descr.weapon_tome_of_the_eternal_flow_1",
      refinementStats: [
        { hp_percent: 16 }, // R1
        { hp_percent: 20 }, // R2
        { hp_percent: 24 }, // R3
        { hp_percent: 28 }, // R4
        { hp_percent: 32 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_tome_of_the_eternal_flow",
      serializeId: 1,
      title: "talent_name.weapon_tome_of_the_eternal_flow",
      description: "talent_descr.weapon_tome_of_the_eternal_flow_2",
      maxStacks: 3,
      refinementStats: [
        { dmg_charged: 14 }, // R1
        { dmg_charged: 18 }, // R2
        { dmg_charged: 22 }, // R3
        { dmg_charged: 26 }, // R4
        { dmg_charged: 30 }, // R5
      ],
    },
    // The 3rd raw condition (ConditionStaticRefine gated by ConditionBooleanValue) only carries
    // text_value (display-only) — omitted as it contributes nothing to damage output.
  ],
};
