// GENERATED by gen-armory.mjs — do not edit
/**
 * toukabou_shigure — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/ToukabouShigure.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { ToukabouShigureStatTable } from "../generated/weaponStatTables.js";

export const toukabouShigure: DbObjectWeapon = {
  name: "toukabou_shigure",
  serializeId: 140,
  gameId: 11422,
  rarity: 4,
  weapon: "sword",
  statTable: ToukabouShigureStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "whisper_toukabou_shigure",
      serializeId: 1,
      title: "talent_name.whisper_toukabou_shigure",
      description: "talent_descr.whisper_toukabou_shigure",
      refinementStats: [
        { dmg_all: 16 }, // R1
        { dmg_all: 20 }, // R2
        { dmg_all: 24 }, // R3
        { dmg_all: 28 }, // R4
        { dmg_all: 32 }, // R5
      ],
    },
  ],
};
