// GENERATED by gen-armory.mjs — do not edit
/**
 * travelers_handy_sword — 3★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/TravelersHandySword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { TravelersHandySwordStatTable } from "../generated/weaponStatTables.js";

export const travelersHandySword: DbObjectWeapon = {
  name: "travelers_handy_sword",
  serializeId: 22,
  gameId: 11303,
  rarity: 3,
  weapon: "sword",
  statTable: TravelersHandySwordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_travelers_handy_sword",
      description: "talent_descr.weapon_travelers_handy_sword",
      refinementStats: [

      ],
    },
  ],
};
