// GENERATED by gen-armory.mjs — do not edit
/**
 * tulaytullahs_remembrance — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/TulaytullahsRemembrance.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { TulaytullahsRemembranceStatTable } from "../generated/weaponStatTables.js";

export const tulaytullahsRemembrance: DbObjectWeapon = {
  name: "tulaytullahs_remembrance",
  serializeId: 139,
  gameId: 14512,
  rarity: 5,
  weapon: "catalyst",
  statTable: TulaytullahsRemembranceStatTable,
  conditions: [
    {
      type: "refine",
      name: "weapon_tulaytullahs_remembrance",
      serializeId: 1,
      title: "talent_name.weapon_tulaytullahs_remembrance",
      description: "talent_descr.weapon_tulaytullahs_remembrance_1",
      refinementStats: [
        { atk_speed_normal: 10 }, // R1
        { atk_speed_normal: 12.5 }, // R2
        { atk_speed_normal: 15 }, // R3
        { atk_speed_normal: 17.5 }, // R4
        { atk_speed_normal: 20 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_tulaytullahs_remembrance_2",
      serializeId: 2,
      title: "talent_name.weapon_tulaytullahs_remembrance",
      description: "talent_descr.weapon_tulaytullahs_remembrance_2",
      maxStacks: 10,
      refinementStats: [
        { dmg_normal: 4.8 }, // R1
        { dmg_normal: 6 }, // R2
        { dmg_normal: 7.2 }, // R3
        { dmg_normal: 8.4 }, // R4
        { dmg_normal: 9.6 }, // R5
      ],
    },
  ],
};
