// GENERATED by gen-armory.mjs — do not edit
/**
 * twin_nephrite — 3★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/TwinNephrite.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { TwinNephriteStatTable } from "../generated/weaponStatTables.js";

export const twinNephrite: DbObjectWeapon = {
  name: "twin_nephrite",
  serializeId: 57,
  gameId: 14305,
  rarity: 3,
  weapon: "catalyst",
  statTable: TwinNephriteStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_twin_nephrite",
      serializeId: 1,
      title: "talent_name.weapon_twin_nephrite",
      description: "talent_descr.weapon_twin_nephrite",
      refinementStats: [
        { atk_percent: 12, move_speed: 12 }, // R1
        { atk_percent: 14, move_speed: 14 }, // R2
        { atk_percent: 16, move_speed: 16 }, // R3
        { atk_percent: 18, move_speed: 18 }, // R4
        { atk_percent: 20, move_speed: 20 }, // R5
      ],
    },
  ],
};
