// GENERATED by gen-armory.mjs — do not edit
/**
 * ultimate_overlords_mega_magic_sword — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/MegaMagicSword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { MegaMagicSwordStatTable } from "../generated/weaponStatTables.js";

export const ultimateOverlordsMegaMagicSword: DbObjectWeapon = {
  name: "ultimate_overlords_mega_magic_sword",
  serializeId: 167,
  gameId: 12426,
  rarity: 4,
  weapon: "claymore",
  statTable: MegaMagicSwordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_ultimate_overlords_mega_magic_sword",
      description: "talent_descr.weapon_ultimate_overlords_mega_magic_sword_1",
      refinementStats: [
        { atk_percent: 12 }, // R1
        { atk_percent: 15 }, // R2
        { atk_percent: 18 }, // R3
        { atk_percent: 21 }, // R4
        { atk_percent: 24 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_ultimate_overlords_mega_magic_sword",
      serializeId: 2,
      title: "talent_name.weapon_ultimate_overlords_mega_magic_sword",
      description: "talent_descr.weapon_ultimate_overlords_mega_magic_sword_2",
      maxStacks: 12,
      refinementStats: [
        { atk_percent: 1 }, // R1
        { atk_percent: 1.25 }, // R2
        { atk_percent: 1.5 }, // R3
        { atk_percent: 1.75 }, // R4
        { atk_percent: 2 }, // R5
      ],
    },
  ],
};
