// GENERATED by gen-armory.mjs — do not edit
/**
 * uraku_misugiri — 5★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/UrakuMisugiri.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { UrakuMisugiriStatTable } from "../generated/weaponStatTables.js";

export const urakuMisugiri: DbObjectWeapon = {
  name: "uraku_misugiri",
  serializeId: 170,
  gameId: 11514,
  rarity: 5,
  weapon: "sword",
  statTable: UrakuMisugiriStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_uraku_misugiri",
      description: "talent_descr.weapon_uraku_misugiri_1",
      refinementStats: [
        { dmg_normal: 16, dmg_skill: 24 }, // R1
        { dmg_normal: 20, dmg_skill: 30 }, // R2
        { dmg_normal: 24, dmg_skill: 36 }, // R3
        { dmg_normal: 28, dmg_skill: 42 }, // R4
        { dmg_normal: 32, dmg_skill: 48 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_uraku_misugiri",
      serializeId: 1,
      title: "talent_name.weapon_uraku_misugiri",
      description: "talent_descr.weapon_uraku_misugiri_2",
      refinementStats: [
        { dmg_normal: 16, dmg_skill: 24 }, // R1
        { dmg_normal: 20, dmg_skill: 30 }, // R2
        { dmg_normal: 24, dmg_skill: 36 }, // R3
        { dmg_normal: 28, dmg_skill: 42 }, // R4
        { dmg_normal: 32, dmg_skill: 48 }, // R5
      ],
    },
    {
      type: "refine",
      title: "talent_name.weapon_uraku_misugiri",
      description: "talent_descr.weapon_uraku_misugiri_3",
      refinementStats: [
        { def_percent: 20 }, // R1
        { def_percent: 25 }, // R2
        { def_percent: 30 }, // R3
        { def_percent: 35 }, // R4
        { def_percent: 40 }, // R5
      ],
    },
  ],
};
