// GENERATED by gen-armory.mjs — do not edit
/**
 * verdict — 5★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/Verdict.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { VerdictStatTable } from "../generated/weaponStatTables.js";

export const verdict: DbObjectWeapon = {
  name: "verdict",
  serializeId: 168,
  gameId: 12512,
  rarity: 5,
  weapon: "claymore",
  statTable: VerdictStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_verdict",
      description: "talent_descr.weapon_verdict_1",
      refinementStats: [
        { atk_percent: 20 }, // R1
        { atk_percent: 25 }, // R2
        { atk_percent: 30 }, // R3
        { atk_percent: 35 }, // R4
        { atk_percent: 40 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_verdict",
      serializeId: 1,
      title: "talent_name.weapon_verdict",
      description: "talent_descr.weapon_verdict_2",
      maxStacks: 2,
      refinementStats: [
        { dmg_skill: 18 }, // R1
        { dmg_skill: 22.5 }, // R2
        { dmg_skill: 27 }, // R3
        { dmg_skill: 31.5 }, // R4
        { dmg_skill: 36 }, // R5
      ],
    },
  ],
};
