// GENERATED by gen-armory.mjs — do not edit
/**
 * vivid_notions — 5★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/VividNotions.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { VividNotionsStatTable } from "../generated/weaponStatTables.js";

export const vividNotions: DbObjectWeapon = {
  name: "vivid_notions",
  serializeId: 198,
  gameId: 14519,
  rarity: 5,
  weapon: "catalyst",
  statTable: VividNotionsStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_vivid_notions",
      description: "talent_descr.weapon_vivid_notions_1",
      refinementStats: [
        { atk_percent: 28 }, // R1
        { atk_percent: 35 }, // R2
        { atk_percent: 42 }, // R3
        { atk_percent: 49 }, // R4
        { atk_percent: 56 }, // R5
      ],
    },
    {
      type: "refine",
      title: "talent_name.weapon_vivid_notions",
      description: "talent_descr.weapon_vivid_notions_2",
      refinementStats: [

      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_vivid_notions_3_1",
      serializeId: 1,
      title: "talent_name.weapon_vivid_notions_3_1",
      description: "talent_descr.weapon_vivid_notions_3",
      refinementStats: [
        { crit_dmg_plunge: 28 }, // R1
        { crit_dmg_plunge: 35 }, // R2
        { crit_dmg_plunge: 42 }, // R3
        { crit_dmg_plunge: 49 }, // R4
        { crit_dmg_plunge: 56 }, // R5
      ],
    },
    {
      type: "boolean-refine",
      name: "weapon_vivid_notions_3_2",
      serializeId: 2,
      title: "talent_name.weapon_vivid_notions_3_2",
      description: "talent_descr.weapon_vivid_notions_3",
      refinementStats: [
        { crit_dmg_plunge: 40 }, // R1
        { crit_dmg_plunge: 50 }, // R2
        { crit_dmg_plunge: 60 }, // R3
        { crit_dmg_plunge: 70 }, // R4
        { crit_dmg_plunge: 80 }, // R5
      ],
    },
  ],
};
