// GENERATED by gen-armory.mjs — do not edit
/**
 * vortex_vanquisher — 5★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/VortexVanquisher.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { VortexVanquisherStatTable } from "../generated/weaponStatTables.js";

export const vortexVanquisher: DbObjectWeapon = {
  name: "vortex_vanquisher",
  serializeId: 93,
  gameId: 13504,
  rarity: 5,
  weapon: "polearm",
  statTable: VortexVanquisherStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_golden_majesty",
      description: "talent_descr.weapon_golden_majesty_passive",
      refinementStats: [
        { shield: 20 }, // R1
        { shield: 25 }, // R2
        { shield: 30 }, // R3
        { shield: 35 }, // R4
        { shield: 40 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_vortex_vanquisher",
      serializeId: 1,
      title: "talent_name.weapon_golden_majesty",
      description: "talent_descr.weapon_golden_majesty",
      maxStacks: 5,
      refinementStats: [
        { atk_percent: 8 }, // R1
        { atk_percent: 10 }, // R2
        { atk_percent: 12 }, // R3
        { atk_percent: 14 }, // R4
        { atk_percent: 16 }, // R5
      ],
    },
  ],
};
