// GENERATED by gen-armory.mjs — do not edit
/**
 * weapon_dialogues_of_the_desert_sages — 4★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/DialoguesOfTheDesertSages.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { DialoguesOfTheDesertSagesStatTable } from "../generated/weaponStatTables.js";

export const weaponDialoguesOfTheDesertSages: DbObjectWeapon = {
  name: "weapon_dialogues_of_the_desert_sages",
  serializeId: 171,
  gameId: 13426,
  rarity: 4,
  weapon: "polearm",
  statTable: DialoguesOfTheDesertSagesStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_dialogues_of_the_desert_sages",
      description: "talent_descr.weapon_dialogues_of_the_desert_sages",
      refinementStats: [

      ],
    },
  ],
};
