// GENERATED by gen-armory.mjs — do not edit
/**
 * whiteblind — 4★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/Whiteblind.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { WhiteblindStatTable } from "../generated/weaponStatTables.js";

export const whiteblind: DbObjectWeapon = {
  name: "whiteblind",
  serializeId: 72,
  gameId: 12407,
  rarity: 4,
  weapon: "claymore",
  statTable: WhiteblindStatTable,
  conditions: [
    {
      type: "stacks",
      name: "weapon_whiteblind",
      serializeId: 1,
      title: "talent_name.weapon_infusion_blade",
      description: "talent_descr.weapon_infusion_blade",
      maxStacks: 4,
      refinementStats: [
        { atk_percent: 6, def_percent: 6 }, // R1
        { atk_percent: 7.5, def_percent: 7.5 }, // R2
        { atk_percent: 9, def_percent: 9 }, // R3
        { atk_percent: 10.5, def_percent: 10.5 }, // R4
        { atk_percent: 12, def_percent: 12 }, // R5
      ],
    },
  ],
};
