// GENERATED by gen-armory.mjs — do not edit
/**
 * white_tassel — 3★ polearm
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Polearm/WhiteTassel.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { WhiteTasselStatTable } from "../generated/weaponStatTables.js";

export const whiteTassel: DbObjectWeapon = {
  name: "white_tassel",
  serializeId: 84,
  gameId: 13301,
  rarity: 3,
  weapon: "polearm",
  statTable: WhiteTasselStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_white_tassel",
      description: "talent_descr.weapon_white_tassel",
      refinementStats: [
        { dmg_normal: 24 }, // R1
        { dmg_normal: 30 }, // R2
        { dmg_normal: 36 }, // R3
        { dmg_normal: 42 }, // R4
        { dmg_normal: 48 }, // R5
      ],
    },
  ],
};
