// GENERATED by gen-armory.mjs — do not edit
/**
 * white_iron_greatsword — 3★ claymore
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Claymore/WhiteIronGreatsword.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { WhiteIronGreatswordStatTable } from "../generated/weaponStatTables.js";

export const whiteIronGreatsword: DbObjectWeapon = {
  name: "white_iron_greatsword",
  serializeId: 79,
  gameId: 12303,
  rarity: 3,
  weapon: "claymore",
  statTable: WhiteIronGreatswordStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_cull_the_weal",
      description: "talent_descr.weapon_cull_the_weal",
      refinementStats: [

      ],
    },
  ],
};
