// GENERATED by gen-armory.mjs — do not edit
/**
 * windblume_ode — 4★ bow
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Bow/WindblumeOde.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { WindblumeOdeStatTable } from "../generated/weaponStatTables.js";

export const windblumeOde: DbObjectWeapon = {
  name: "windblume_ode",
  serializeId: 41,
  gameId: 15413,
  rarity: 4,
  weapon: "bow",
  statTable: WindblumeOdeStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_windblume_ode",
      serializeId: 1,
      title: "talent_name.weapon_windblume_ode",
      description: "talent_descr.weapon_windblume_ode",
      refinementStats: [
        { atk_percent: 16 }, // R1
        { atk_percent: 20 }, // R2
        { atk_percent: 24 }, // R3
        { atk_percent: 28 }, // R4
        { atk_percent: 32 }, // R5
      ],
    },
  ],
};
