// GENERATED by gen-armory.mjs — do not edit
/**
 * wine_and_song — 4★ catalyst
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Catalyst/WineAndSong.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { WineandSongStatTable } from "../generated/weaponStatTables.js";

export const wineAndSong: DbObjectWeapon = {
  name: "wine_and_song",
  serializeId: 46,
  gameId: 14410,
  rarity: 4,
  weapon: "catalyst",
  statTable: WineandSongStatTable,
  conditions: [
    {
      type: "boolean-refine",
      name: "weapon_wine_and_song",
      serializeId: 1,
      title: "talent_name.weapon_wine_and_song",
      description: "talent_descr.weapon_wine_and_song",
      refinementStats: [
        { atk_percent: 20 }, // R1
        { atk_percent: 25 }, // R2
        { atk_percent: 30 }, // R3
        { atk_percent: 35 }, // R4
        { atk_percent: 40 }, // R5
      ],
    },
  ],
};
