// GENERATED by gen-armory.mjs — do not edit
/**
 * wolf_fang — 4★ sword
 *
 * Faithful 1:1 port of her raw DbObjectWeapon (conditions serialized from the live
 * object; stat values live in the generated statTable, referenced by key).
 * Source: raw/genshin_calc_pub/src/js/db/Weapon/Sword/WolfFang.js
 */

import type { DbObjectWeapon } from "@genshin/types";
import { WolfFangStatTable } from "../generated/weaponStatTables.js";

export const wolfFang: DbObjectWeapon = {
  name: "wolf_fang",
  serializeId: 146,
  gameId: 11424,
  rarity: 4,
  weapon: "sword",
  statTable: WolfFangStatTable,
  conditions: [
    {
      type: "refine",
      title: "talent_name.weapon_wolf_fang",
      description: "talent_descr.weapon_wolf_fang_1",
      refinementStats: [
        { dmg_skill: 16, dmg_burst: 16 }, // R1
        { dmg_skill: 20, dmg_burst: 20 }, // R2
        { dmg_skill: 24, dmg_burst: 24 }, // R3
        { dmg_skill: 28, dmg_burst: 28 }, // R4
        { dmg_skill: 32, dmg_burst: 32 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_wolf_fang_1",
      serializeId: 1,
      title: "talent_name.weapon_wolf_fang_2",
      description: "talent_descr.weapon_wolf_fang_2",
      maxStacks: 4,
      refinementStats: [
        { crit_rate_skill: 2 }, // R1
        { crit_rate_skill: 2.5 }, // R2
        { crit_rate_skill: 3 }, // R3
        { crit_rate_skill: 3.5 }, // R4
        { crit_rate_skill: 4 }, // R5
      ],
    },
    {
      type: "stacks",
      name: "weapon_wolf_fang_2",
      serializeId: 2,
      title: "talent_name.weapon_wolf_fang_3",
      description: "talent_descr.weapon_wolf_fang_3",
      maxStacks: 4,
      refinementStats: [
        { crit_rate_burst: 2 }, // R1
        { crit_rate_burst: 2.5 }, // R2
        { crit_rate_burst: 3 }, // R3
        { crit_rate_burst: 3.5 }, // R4
        { crit_rate_burst: 4 }, // R5
      ],
    },
  ],
};
