import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Arc B ("food drawer + custom buffs") e2e coverage: the Food drawer's live
 * damage-delta ranking (Task 4) and the Custom Buffs section in the Buffs &
 * Team drawer (Task 5). Engine-side expectations live in
 * e2e/fixtures/food-custom.json, regenerated by
 * lib/__tests__/sweepExpectations.gen.test.ts on every unit-test run
 * (Playwright's runner cannot import the ESM-only @genshin/data directly —
 * same rationale as results-depth.spec.ts).
 */

interface FoodCase {
  hashBase: string;
  hashFood: string;
  dishKey: string;
  tier: number;
  expectedHeadlineBase: number;
  expectedHeadlineFood: number;
}

interface CustomCase {
  hashBase: string;
  hashCustom: string;
  expectedAtkTotalBase: number;
  expectedAtkTotalCustom: number;
}

interface Fixture {
  food: FoodCase;
  custom: CustomCase;
}

const fixture: Fixture = JSON.parse(
  readFileSync(join(__dirname, "fixtures", "food-custom.json"), "utf8")
);

// Same formatter the app uses for every rendered stat/damage number
// (lib/motion.ts's `fmt`, lib/statSheet.ts's `fmtFlat`, Breakdown.tsx's `fmt`).
const fmt = (n: number) => Math.round(n).toLocaleString("en-US");

test("equipping a food dish from the Food drawer moves the pinned headline", async ({ page }) => {
  await page.goto(`/#${fixture.food.hashBase}`);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.food.expectedHeadlineBase), {
    timeout: 10_000,
  });

  await page.getByRole("tab", { name: "Food", exact: true }).click();
  await page.getByTestId(`food-row-${fixture.food.dishKey}-${fixture.food.tier}`).click();

  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.food.expectedHeadlineFood), {
    timeout: 5_000,
  });
});

test("un-equipping the equipped food dish restores the base headline", async ({ page }) => {
  await page.goto(`/#${fixture.food.hashFood}`);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.food.expectedHeadlineFood), {
    timeout: 10_000,
  });

  await page.getByRole("tab", { name: "Food", exact: true }).click();
  const row = page.getByTestId(`food-row-${fixture.food.dishKey}-${fixture.food.tier}`);
  await expect(row.getByText("Equipped")).toBeVisible();
  await row.click();

  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.food.expectedHeadlineBase), {
    timeout: 5_000,
  });
});

test("a custom ATK buff raises the Stats tab's ATK total", async ({ page }) => {
  await page.goto(`/#${fixture.custom.hashBase}`);
  await expect(page.getByTestId("result-avg").first()).toBeVisible({ timeout: 10_000 });

  await page.getByRole("tab", { name: "Buffs", exact: true }).click();
  await page.getByTestId("custom-buffs-section").click();
  await page.getByTestId("custom-buff-atk").fill("500");

  // Close the drawer — its fixed backdrop overlays the results pane and would
  // otherwise block the Stats tab click underneath.
  await page.getByRole("tab", { name: "Buffs", exact: true }).click();

  await page.getByTestId("results-tab-stats").click();
  await expect(page.getByTestId("stat-total-atk_total")).toHaveText(
    fmt(fixture.custom.expectedAtkTotalCustom)
  );
});
