import { test, expect, type Page, type Locator } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Arc C ("saved builds") e2e coverage: the Builds drawer's localStorage
 * persistence — save/list-ordering/reload-survival/load/search/delete, plus
 * the two review-fix guards from Task 2 (load = full form replace, Esc
 * cancels an in-flight rename). Engine-side expectations live in
 * e2e/fixtures/saved-builds.json, regenerated by
 * lib/__tests__/sweepExpectations.gen.test.ts on every unit-test run — same
 * rationale as the other e2e fixtures (Playwright can't import the ESM-only
 * @genshin/data directly).
 *
 * Saved builds live in localStorage, so — unlike every other spec in this
 * suite — these tests are stateful. Playwright gives each `test()` a fresh
 * browser context (and therefore fresh localStorage) by default; we also
 * clear it explicitly at the top of every test as a defense-in-depth
 * belt-and-suspenders measure, since a future config change (e.g. a shared
 * `storageState`) could otherwise silently leak state between tests.
 */

interface Fixture {
  hashA: string;
  hashB: string;
  expectedHeadlineA: number;
  expectedHeadlineB: number;
  pinKey: string;
  pinnedHeadline: number;
}

const fixture: Fixture = JSON.parse(
  readFileSync(join(__dirname, "fixtures", "saved-builds.json"), "utf8")
);

// Same formatter the app uses for every rendered stat/damage number
// (lib/motion.ts's `fmt`, lib/statSheet.ts's `fmtFlat`, Breakdown.tsx's `fmt`).
const fmt = (n: number) => Math.round(n).toLocaleString("en-US");

async function clearSavedBuilds(page: Page): Promise<void> {
  await page.evaluate(() => localStorage.clear());
}

/**
 * Navigates to a build hash. The app only reads `window.location.hash` on
 * mount (`app/page.tsx`), and a hash-only URL change is a same-document
 * navigation that does NOT remount the page — so switching from one saved
 * build's hash to another within a test needs an explicit reload to force
 * the app to re-hydrate from the new hash.
 */
async function gotoBuild(page: Page, hash: string): Promise<void> {
  await page.goto(`/#${hash}`);
  await page.reload();
}

/** Opens (or closes, since the rail button toggles) the Builds drawer. */
async function toggleBuilds(page: Page): Promise<void> {
  await page.getByRole("tab", { name: "Builds", exact: true }).click();
}

function rowByTitle(page: Page, title: string): Locator {
  return page.locator('[data-testid^="build-row-"]').filter({ hasText: title });
}

/** Two-step confirm: both clicks land well inside the 3s auto-disarm window. */
async function armThenConfirm(locator: Locator): Promise<void> {
  await locator.click();
  await locator.click();
}

async function saveCurrentAs(page: Page, title: string): Promise<void> {
  await toggleBuilds(page);
  await expect(page.getByTestId("builds-save-name")).toBeVisible();
  await page.getByTestId("builds-save-name").fill(title);
  await page.getByTestId("builds-save").click();
  await expect(rowByTitle(page, title)).toBeVisible();
}

test("saving two builds lists them with the most recently saved first", async ({ page }) => {
  await gotoBuild(page, fixture.hashA);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 10_000,
  });

  await saveCurrentAs(page, "Alpha");

  await gotoBuild(page, fixture.hashB);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineB), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Beta");

  const rows = page.locator('[data-testid^="build-row-"]');
  await expect(rows).toHaveCount(2);
  await expect(rows.nth(0)).toContainText("Beta");
  await expect(rows.nth(1)).toContainText("Alpha");
});

test("saved builds persist across a page reload", async ({ page }) => {
  await gotoBuild(page, fixture.hashA);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Alpha");

  await gotoBuild(page, fixture.hashB);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineB), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Beta");

  await page.reload();
  await toggleBuilds(page);

  const rows = page.locator('[data-testid^="build-row-"]');
  await expect(rows).toHaveCount(2);
  await expect(rows.nth(0)).toContainText("Beta");
  await expect(rows.nth(1)).toContainText("Alpha");
});

test("loading a saved build replaces the current headline with the saved build's", async ({ page }) => {
  await gotoBuild(page, fixture.hashA);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Alpha");

  await gotoBuild(page, fixture.hashB);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineB), {
    timeout: 10_000,
  });
  await toggleBuilds(page);

  const loadBtn = rowByTitle(page, "Alpha").locator('[data-testid^="build-load-"]');
  await armThenConfirm(loadBtn);

  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 5_000,
  });
});

test("the search box filters the saved builds list by title", async ({ page }) => {
  await gotoBuild(page, fixture.hashA);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Alpha");

  await gotoBuild(page, fixture.hashB);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineB), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Beta");

  // Case-insensitive substring on title.
  await page.getByTestId("builds-search").fill("alp");

  const rows = page.locator('[data-testid^="build-row-"]');
  await expect(rows).toHaveCount(1);
  await expect(rows.first()).toContainText("Alpha");
});

test("deleting a saved build removes it, and the deletion survives reload", async ({ page }) => {
  await gotoBuild(page, fixture.hashA);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Alpha");

  await gotoBuild(page, fixture.hashB);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineB), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Beta");

  const betaRow = rowByTitle(page, "Beta");
  await betaRow.locator('[data-testid^="build-menu-"]').click();
  await armThenConfirm(betaRow.locator('[data-testid^="build-delete-"]'));

  await expect(page.locator('[data-testid^="build-row-"]')).toHaveCount(1);
  await expect(rowByTitle(page, "Alpha")).toBeVisible();

  await page.reload();
  await toggleBuilds(page);
  await expect(page.locator('[data-testid^="build-row-"]')).toHaveCount(1);
  await expect(rowByTitle(page, "Alpha")).toBeVisible();
});

test("loading a build without a pinned feature clears a stale pin from the current form", async ({ page }) => {
  await gotoBuild(page, fixture.hashB);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineB), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Beta");

  // Close the drawer — its fixed backdrop overlays the Breakdown pane and
  // would otherwise intercept the pin-button click underneath.
  await toggleBuilds(page);

  await page.getByTestId(`pin-${fixture.pinKey}`).click();
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.pinnedHeadline), {
    timeout: 5_000,
  });

  await toggleBuilds(page);
  const loadBtn = rowByTitle(page, "Beta").locator('[data-testid^="build-load-"]');
  await armThenConfirm(loadBtn);

  // Beta's saved hash carries no pinnedFeature — a true full-form replace
  // (not a merge) must clear the pin the click above set, reverting the
  // headline to Beta's own highest-average feature.
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineB), {
    timeout: 5_000,
  });
});

test("pressing Escape while renaming cancels the edit and keeps the original title", async ({ page }) => {
  await gotoBuild(page, fixture.hashA);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Alpha");

  // A plain testid-prefix locator, not `rowByTitle` — once renaming starts,
  // the title span is replaced by an <input>, so a `hasText` filter keyed on
  // the old title would stop matching the row (only one build exists here).
  const alphaRow = page.locator('[data-testid^="build-row-"]').first();
  await expect(alphaRow).toContainText("Alpha");
  await alphaRow.locator('[data-testid^="build-menu-"]').click();
  await alphaRow.locator('[data-testid^="build-rename-"]').click();

  const renameInput = alphaRow.locator("input");
  await expect(renameInput).toBeVisible();
  await renameInput.fill("Changed");
  await renameInput.press("Escape");

  await expect(alphaRow).toContainText("Alpha");
  await expect(alphaRow).not.toContainText("Changed");
});

test("clicking outside an open row menu closes it", async ({ page }) => {
  await gotoBuild(page, fixture.hashA);
  await clearSavedBuilds(page);
  await expect(page.getByTestId("headline-avg")).toHaveText(fmt(fixture.expectedHeadlineA), {
    timeout: 10_000,
  });
  await saveCurrentAs(page, "Alpha");

  const alphaRow = page.locator('[data-testid^="build-row-"]').first();
  await alphaRow.locator('[data-testid^="build-menu-"]').click();
  await expect(alphaRow.locator('[data-testid^="build-rename-"]')).toBeVisible();

  // Click somewhere well outside the row (the search input) — the menu
  // should close via the document-level mousedown listener.
  await page.getByTestId("builds-search").click();
  await expect(alphaRow.locator('[data-testid^="build-rename-"]')).toBeHidden();
});
