import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Post-sweep verification: the self-buff parity arc (2026-07) ported ~108
 * characters' self conditions into @genshin/data. These tests assert the
 * WEBSITE surfaces that work: for sweep-fixed characters, the self-buff
 * controls render in the Build drawer, and the buff-moved feature value the
 * engine computes for the all-buffs-on build is what the page renders.
 *
 * Engine-side expectations live in e2e/fixtures/sweep-selfbuffs.json,
 * regenerated by lib/__tests__/sweepExpectations.gen.test.ts on every unit-test
 * run (Playwright's runner cannot import the ESM-only @genshin/data directly).
 */

interface FixtureEntry {
  char: string;
  hash: string;
  featureKey: string;
  expectedOn: number;
  expectedOff: number | null;
  firstLabel: string;
}

const entries: FixtureEntry[] = JSON.parse(
  readFileSync(join(__dirname, "fixtures", "sweep-selfbuffs.json"), "utf8")
);

const fmt = (n: number) => n.toLocaleString("en-US");

for (const entry of entries) {
  test(`${entry.char}: self buffs surface in UI and match engine (${entry.featureKey})`, async ({
    page,
  }) => {
    await page.goto(`/#${entry.hash}`);

    // Results render for this character at all.
    await expect(page.getByTestId("result-avg").first()).toBeVisible({ timeout: 10_000 });

    // The engine's buffed value for the most buff-moved feature appears on the
    // page (top-level row or nested part — both render fmt'd averages).
    await expect(
      page.getByText(fmt(entry.expectedOn), { exact: true }).first()
    ).toBeVisible({ timeout: 5_000 });

    // The self controls render in the Build drawer.
    await page.getByRole("button", { name: "Build", exact: true }).click();
    await expect(
      page.getByText(entry.firstLabel, { exact: false }).first()
    ).toBeVisible({ timeout: 5_000 });
  });
}
