// GENERATED by gen-armory.mjs — do not edit
/**
 * Adventurer — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "Adventurer". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/Adventurer.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const adventurer: DbObjectArtifactSet = {
  name: "artifact_set.adventurer",
  goodId: "Adventurer",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.adventurer_2",
          description: "set_descr.adventurer_2",
          stats: { hp: 1000 },
        },
      ],
    },
  },
};
