// GENERATED by gen-armory.mjs — do not edit
/**
 * Berserker — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "Berserker". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/Berserker.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const berserker: DbObjectArtifactSet = {
  name: "artifact_set.berserker",
  goodId: "Berserker",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.berserker_2",
          description: "set_descr.berserker_2",
          stats: { crit_rate: 12 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "set.berserker_4",
          serializeId: 1,
          title: "set_bonus.berserker_4",
          description: "set_descr.berserker_4",
          stats: { crit_rate: 24 },
        },
      ],
    },
  },
};
