// GENERATED by gen-armory.mjs — do not edit
/**
 * BloodstainedChivalry — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "BloodstainedChivalry". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/BloodstainedChivalry.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const bloodstainedChivalry: DbObjectArtifactSet = {
  name: "artifact_set.bloodstained_chivalry",
  goodId: "BloodstainedChivalry",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.bloodstained_chivalry_2",
          description: "set_descr.bloodstained_chivalry_2",
          stats: { dmg_phys: 25 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "set.bloodstained_chivalry_4",
          serializeId: 4,
          title: "set_bonus.bloodstained_chivalry_4",
          description: "set_descr.bloodstained_chivalry_4",
          stats: { dmg_charged: 50 },
        },
      ],
    },
  },
};
