// GENERATED by gen-armory.mjs — do not edit
/**
 * BraveHeart — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "BraveHeart". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/BraveHeart.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const braveHeart: DbObjectArtifactSet = {
  name: "artifact_set.brave_heart",
  goodId: "BraveHeart",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.brave_heart_2",
          description: "set_descr.brave_heart_2",
          stats: { atk_percent: 18 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "brave_heart_4",
          serializeId: 5,
          title: "set_bonus.brave_heart_4",
          description: "set_descr.brave_heart_4",
          stats: { dmg_all: 30 },
        },
      ],
    },
  },
};
