// GENERATED by gen-armory.mjs — do not edit
/**
 * DesertPavilionChronicle — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "DesertPavilionChronicle". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/DesertPavilionChronicle.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const desertPavilionChronicle: DbObjectArtifactSet = {
  name: "artifact_set.desert_pavilion_chronicle",
  goodId: "DesertPavilionChronicle",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.desert_pavilion_chronicle_2",
          description: "set_descr.desert_pavilion_chronicle_2",
          stats: { dmg_anemo: 15 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "set.desert_pavilion_chronicle_4",
          serializeId: 29,
          title: "set_bonus.desert_pavilion_chronicle_4",
          description: "set_descr.desert_pavilion_chronicle_4",
          stats: { atk_speed_normal: 10, dmg_normal: 40, dmg_charged: 40, dmg_plunge: 40 },
        },
      ],
    },
  },
};
