// GENERATED by gen-armory.mjs — do not edit
/**
 * FlowerOfParadiseLost — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "FlowerOfParadiseLost". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/FlowerOfParadiseLost.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const flowerOfParadiseLost: DbObjectArtifactSet = {
  name: "artifact_set.flower_of_paradise_lost",
  goodId: "FlowerOfParadiseLost",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.flower_of_paradise_lost_2",
          description: "set_descr.flower_of_paradise_lost_2",
          stats: { mastery: 80 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.flower_of_paradise_lost_4",
          description: "set_descr.flower_of_paradise_lost_4_1",
          stats: { dmg_reaction_bloom: 40 },
        },
        {
          type: "stacks",
          name: "set.flower_of_paradise_lost_4",
          serializeId: 30,
          title: "set_bonus.flower_of_paradise_lost_4",
          description: "set_descr.flower_of_paradise_lost_4_2",
          maxStacks: 4,
          stats: { dmg_reaction_bloom: 10 },
        },
      ],
    },
  },
};
