// GENERATED by gen-armory.mjs — do not edit
/**
 * FragmentOfHarmonicWhimsy — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "FragmentOfHarmonicWhimsy". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/FragmentOfHarmonicWhimsy.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const fragmentOfHarmonicWhimsy: DbObjectArtifactSet = {
  name: "artifact_set.fragment_of_harmonic_whimsy",
  goodId: "FragmentOfHarmonicWhimsy",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.fragment_of_harmonic_whimsy_2",
          description: "set_descr.fragment_of_harmonic_whimsy_2",
          stats: { atk_percent: 18 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "stacks",
          name: "set.fragment_of_harmonic_whimsy_4",
          serializeId: 40,
          title: "set_bonus.fragment_of_harmonic_whimsy_4",
          description: "set_descr.fragment_of_harmonic_whimsy_4",
          maxStacks: 3,
          stats: { dmg_all: 18 },
        },
      ],
    },
  },
};
