// GENERATED by gen-armory.mjs — do not edit
/**
 * Gambler — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "Gambler". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/Gambler.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const gambler: DbObjectArtifactSet = {
  name: "artifact_set.gambler",
  goodId: "Gambler",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.gambler_2",
          description: "set_descr.gambler_2",
          stats: { dmg_skill: 20 },
        },
      ],
    },
  },
};
