// GENERATED by tools/port/gen-barrels.mjs — do not edit by hand.
/**
 * Artifact-set registry — `setKey (goodId) -> DbObjectArtifactSet`, full v5.8 armory (58).
 *
 * `goodId` is Aspirine's oracle `art.set` key (the same string `buildStats`'s `setBonuses`
 * input and `build-configs.mjs equipSet` use). It equals the GOOD-format key for most sets
 * but follows her key where they diverge, e.g. "CrimsonWitch" (GOOD: "CrimsonWitchOfFlames"),
 * "HeartofDepth", "EmblemofSeveredFate", "TenacityofMillelith", "ScrollOfTheEmberedCitysHero".
 *
 * The golden harness auto-discovers set files via import.meta.glob independently; this barrel
 * is the production RUNTIME registry (`getArtifactSet`, consumed by buildStats).
 * Regenerate after adding/removing a set file: `node tools/port/gen-barrels.mjs`.
 *
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Sets.js (the set registry)
 */

import type { DbObjectArtifactSet } from "@genshin/types";
import { adventurer } from "./adventurer.js";
import { archaicPetra } from "./archaic-petra.js";
import { aubadeOfMorningstarAndMoon } from "./aubade-of-morningstar-and-moon.js";
import { berserker } from "./berserker.js";
import { blizzardStrayer } from "./blizzard-strayer.js";
import { bloodstainedChivalry } from "./bloodstained-chivalry.js";
import { braveHeart } from "./brave-heart.js";
import { crimsonWitch } from "./crimson-witch.js";
import { deepwoodMemories } from "./deepwood-memories.js";
import { defendersWill } from "./defenders-will.js";
import { desertPavilionChronicle } from "./desert-pavilion-chronicle.js";
import { echoesOfAnOffering } from "./echoes-of-an-offering.js";
import { emblemOfSeveredFate } from "./emblem-of-severed-fate.js";
import { finaleOfTheDeepGalleries } from "./finale-of-the-deep-galleries.js";
import { flowerOfParadiseLost } from "./flower-of-paradise-lost.js";
import { fragmentOfHarmonicWhimsy } from "./fragment-of-harmonic-whimsy.js";
import { gambler } from "./gambler.js";
import { gildedDreams } from "./gilded-dreams.js";
import { gladiatorFinale } from "./gladiator-finale.js";
import { goldenTroupe } from "./golden-troupe.js";
import { heartOfDepth } from "./heart-of-depth.js";
import { huskOfOpulentDreams } from "./husk-of-opulent-dreams.js";
import { instructor } from "./instructor.js";
import { lavawalker } from "./lavawalker.js";
import { longNightsOath } from "./long-nights-oath.js";
import { luckyDog } from "./lucky-dog.js";
import { maidenBeloved } from "./maiden-beloved.js";
import { marechausseeHunter } from "./marechaussee-hunter.js";
import { martialArtist } from "./martial-artist.js";
import { nightOfTheSkysUnveiling } from "./night-of-the-skys-unveiling.js";
import { nighttimeWhispersInTheEchoingWoods } from "./nighttime-whispers-in-the-echoing-woods.js";
import { noblesseOblige } from "./noblesse-oblige.js";
import { nymphsDream } from "./nymphs-dream.js";
import { obsidianCodex } from "./obsidian-codex.js";
import { oceanHuedClam } from "./ocean-hued-clam.js";
import { paleFlame } from "./pale-flame.js";
import { prayersForDestiny } from "./prayers-for-destiny.js";
import { prayersForIllumination } from "./prayers-for-illumination.js";
import { prayersForWisdom } from "./prayers-for-wisdom.js";
import { prayersToSpringtime } from "./prayers-to-springtime.js";
import { resolutionOfSojourner } from "./resolution-of-sojourner.js";
import { retracingBolide } from "./retracing-bolide.js";
import { scholar } from "./scholar.js";
import { scrollOfTheHeroOfCinderCity } from "./scroll-of-the-hero-of-cinder-city.js";
import { shimenawasReminiscence } from "./shimenawas-reminiscence.js";
import { silkenMoonsSerenade } from "./silken-moons-serenade.js";
import { songOfDaysPast } from "./song-of-days-past.js";
import { tenacityOfTheMillelith } from "./tenacity-of-the-millelith.js";
import { theExile } from "./the-exile.js";
import { thunderingFury } from "./thundering-fury.js";
import { thundersoother } from "./thundersoother.js";
import { tinyMiracle } from "./tiny-miracle.js";
import { travelingDoctor } from "./traveling-doctor.js";
import { unfinishedReverie } from "./unfinished-reverie.js";
import { vermillionHereafter } from "./vermillion-hereafter.js";
import { viridescentVenerer } from "./viridescent-venerer.js";
import { vourukashasGlow } from "./vourukashas-glow.js";
import { wanderersTroupe } from "./wanderers-troupe.js";

export { adventurer } from "./adventurer.js";
export { archaicPetra } from "./archaic-petra.js";
export { aubadeOfMorningstarAndMoon } from "./aubade-of-morningstar-and-moon.js";
export { berserker } from "./berserker.js";
export { blizzardStrayer } from "./blizzard-strayer.js";
export { bloodstainedChivalry } from "./bloodstained-chivalry.js";
export { braveHeart } from "./brave-heart.js";
export { crimsonWitch } from "./crimson-witch.js";
export { deepwoodMemories } from "./deepwood-memories.js";
export { defendersWill } from "./defenders-will.js";
export { desertPavilionChronicle } from "./desert-pavilion-chronicle.js";
export { echoesOfAnOffering } from "./echoes-of-an-offering.js";
export { emblemOfSeveredFate } from "./emblem-of-severed-fate.js";
export { finaleOfTheDeepGalleries } from "./finale-of-the-deep-galleries.js";
export { flowerOfParadiseLost } from "./flower-of-paradise-lost.js";
export { fragmentOfHarmonicWhimsy } from "./fragment-of-harmonic-whimsy.js";
export { gambler } from "./gambler.js";
export { gildedDreams } from "./gilded-dreams.js";
export { gladiatorFinale } from "./gladiator-finale.js";
export { goldenTroupe } from "./golden-troupe.js";
export { heartOfDepth } from "./heart-of-depth.js";
export { huskOfOpulentDreams } from "./husk-of-opulent-dreams.js";
export { instructor } from "./instructor.js";
export { lavawalker } from "./lavawalker.js";
export { longNightsOath } from "./long-nights-oath.js";
export { luckyDog } from "./lucky-dog.js";
export { maidenBeloved } from "./maiden-beloved.js";
export { marechausseeHunter } from "./marechaussee-hunter.js";
export { martialArtist } from "./martial-artist.js";
export { nightOfTheSkysUnveiling } from "./night-of-the-skys-unveiling.js";
export { nighttimeWhispersInTheEchoingWoods } from "./nighttime-whispers-in-the-echoing-woods.js";
export { noblesseOblige } from "./noblesse-oblige.js";
export { nymphsDream } from "./nymphs-dream.js";
export { obsidianCodex } from "./obsidian-codex.js";
export { oceanHuedClam } from "./ocean-hued-clam.js";
export { paleFlame } from "./pale-flame.js";
export { prayersForDestiny } from "./prayers-for-destiny.js";
export { prayersForIllumination } from "./prayers-for-illumination.js";
export { prayersForWisdom } from "./prayers-for-wisdom.js";
export { prayersToSpringtime } from "./prayers-to-springtime.js";
export { resolutionOfSojourner } from "./resolution-of-sojourner.js";
export { retracingBolide } from "./retracing-bolide.js";
export { scholar } from "./scholar.js";
export { scrollOfTheHeroOfCinderCity } from "./scroll-of-the-hero-of-cinder-city.js";
export { shimenawasReminiscence } from "./shimenawas-reminiscence.js";
export { silkenMoonsSerenade } from "./silken-moons-serenade.js";
export { songOfDaysPast } from "./song-of-days-past.js";
export { tenacityOfTheMillelith } from "./tenacity-of-the-millelith.js";
export { theExile } from "./the-exile.js";
export { thunderingFury } from "./thundering-fury.js";
export { thundersoother } from "./thundersoother.js";
export { tinyMiracle } from "./tiny-miracle.js";
export { travelingDoctor } from "./traveling-doctor.js";
export { unfinishedReverie } from "./unfinished-reverie.js";
export { vermillionHereafter } from "./vermillion-hereafter.js";
export { viridescentVenerer } from "./viridescent-venerer.js";
export { vourukashasGlow } from "./vourukashas-glow.js";
export { wanderersTroupe } from "./wanderers-troupe.js";

/** All ported sets, keyed by `goodId` (the registry / build-config key). */
export const ARTIFACT_SETS: Readonly<Record<string, DbObjectArtifactSet>> = {
  [adventurer.goodId]: adventurer,
  [archaicPetra.goodId]: archaicPetra,
  [aubadeOfMorningstarAndMoon.goodId]: aubadeOfMorningstarAndMoon,
  [berserker.goodId]: berserker,
  [blizzardStrayer.goodId]: blizzardStrayer,
  [bloodstainedChivalry.goodId]: bloodstainedChivalry,
  [braveHeart.goodId]: braveHeart,
  [crimsonWitch.goodId]: crimsonWitch,
  [deepwoodMemories.goodId]: deepwoodMemories,
  [defendersWill.goodId]: defendersWill,
  [desertPavilionChronicle.goodId]: desertPavilionChronicle,
  [echoesOfAnOffering.goodId]: echoesOfAnOffering,
  [emblemOfSeveredFate.goodId]: emblemOfSeveredFate,
  [finaleOfTheDeepGalleries.goodId]: finaleOfTheDeepGalleries,
  [flowerOfParadiseLost.goodId]: flowerOfParadiseLost,
  [fragmentOfHarmonicWhimsy.goodId]: fragmentOfHarmonicWhimsy,
  [gambler.goodId]: gambler,
  [gildedDreams.goodId]: gildedDreams,
  [gladiatorFinale.goodId]: gladiatorFinale,
  [goldenTroupe.goodId]: goldenTroupe,
  [heartOfDepth.goodId]: heartOfDepth,
  [huskOfOpulentDreams.goodId]: huskOfOpulentDreams,
  [instructor.goodId]: instructor,
  [lavawalker.goodId]: lavawalker,
  [longNightsOath.goodId]: longNightsOath,
  [luckyDog.goodId]: luckyDog,
  [maidenBeloved.goodId]: maidenBeloved,
  [marechausseeHunter.goodId]: marechausseeHunter,
  [martialArtist.goodId]: martialArtist,
  [nightOfTheSkysUnveiling.goodId]: nightOfTheSkysUnveiling,
  [nighttimeWhispersInTheEchoingWoods.goodId]: nighttimeWhispersInTheEchoingWoods,
  [noblesseOblige.goodId]: noblesseOblige,
  [nymphsDream.goodId]: nymphsDream,
  [obsidianCodex.goodId]: obsidianCodex,
  [oceanHuedClam.goodId]: oceanHuedClam,
  [paleFlame.goodId]: paleFlame,
  [prayersForDestiny.goodId]: prayersForDestiny,
  [prayersForIllumination.goodId]: prayersForIllumination,
  [prayersForWisdom.goodId]: prayersForWisdom,
  [prayersToSpringtime.goodId]: prayersToSpringtime,
  [resolutionOfSojourner.goodId]: resolutionOfSojourner,
  [retracingBolide.goodId]: retracingBolide,
  [scholar.goodId]: scholar,
  [scrollOfTheHeroOfCinderCity.goodId]: scrollOfTheHeroOfCinderCity,
  [shimenawasReminiscence.goodId]: shimenawasReminiscence,
  [silkenMoonsSerenade.goodId]: silkenMoonsSerenade,
  [songOfDaysPast.goodId]: songOfDaysPast,
  [tenacityOfTheMillelith.goodId]: tenacityOfTheMillelith,
  [theExile.goodId]: theExile,
  [thunderingFury.goodId]: thunderingFury,
  [thundersoother.goodId]: thundersoother,
  [tinyMiracle.goodId]: tinyMiracle,
  [travelingDoctor.goodId]: travelingDoctor,
  [unfinishedReverie.goodId]: unfinishedReverie,
  [vermillionHereafter.goodId]: vermillionHereafter,
  [viridescentVenerer.goodId]: viridescentVenerer,
  [vourukashasGlow.goodId]: vourukashasGlow,
  [wanderersTroupe.goodId]: wanderersTroupe,
};

/** Resolve a set by its registry key; `undefined` if not ported. */
export function getArtifactSet(setKey: string): DbObjectArtifactSet | undefined {
  return ARTIFACT_SETS[setKey];
}
