// GENERATED by gen-armory.mjs — do not edit
/**
 * LongNightsOath — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "LongNightsOath". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/LongNightsOath.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const longNightsOath: DbObjectArtifactSet = {
  name: "artifact_set.long_nights_oath",
  goodId: "LongNightsOath",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.long_nights_oath_2",
          description: "set_descr.long_nights_oath_2",
          stats: { dmg_plunge: 25 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "stacks",
          name: "set.long_nights_oath_4",
          serializeId: 45,
          title: "set_bonus.long_nights_oath_4",
          description: "set_descr.long_nights_oath_4",
          maxStacks: 5,
          stats: { dmg_plunge: 15 },
        },
      ],
    },
  },
};
