// GENERATED by gen-armory.mjs — do not edit
/**
 * LuckyDog — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "LuckyDog". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/LuckyDog.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const luckyDog: DbObjectArtifactSet = {
  name: "artifact_set.lucky_dog",
  goodId: "LuckyDog",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.lucky_dog_2",
          description: "set_descr.lucky_dog_2",
          stats: { def: 100 },
        },
      ],
    },
  },
};
