// GENERATED by gen-armory.mjs — do not edit
/**
 * MaidenBeloved — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "MaidenBeloved". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/MaidenBeloved.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const maidenBeloved: DbObjectArtifactSet = {
  name: "artifact_set.maiden_beloved",
  goodId: "MaidenBeloved",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.maiden_beloved_2",
          description: "set_descr.maiden_beloved_2",
          stats: { healing: 15 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "set.maiden_beloved_4",
          serializeId: 10,
          title: "set_bonus.maiden_beloved_4",
          description: "set_descr.maiden_beloved_4",
          stats: { healing_recv: 20 },
        },
      ],
    },
  },
};
