// GENERATED by gen-armory.mjs — do not edit
/**
 * MartialArtist — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "MartialArtist". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/MartialArtist.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const martialArtist: DbObjectArtifactSet = {
  name: "artifact_set.martial_artist",
  goodId: "MartialArtist",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.martial_artist_2",
          description: "set_descr.martial_artist_2",
          stats: { dmg_normal: 15, dmg_charged: 15 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "set.martial_artist_4",
          serializeId: 11,
          title: "set_bonus.martial_artist_4",
          description: "set_descr.martial_artist_4",
          stats: { dmg_normal: 25, dmg_charged: 25 },
        },
      ],
    },
  },
};
