// GENERATED by gen-armory.mjs — do not edit
/**
 * NighttimeWhispersInTheEchoingWoods — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "NighttimeWhispersInTheEchoingWoods". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/NighttimeWhispersInTheEchoingWoods.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const nighttimeWhispersInTheEchoingWoods: DbObjectArtifactSet = {
  name: "artifact_set.nighttime_whispers_in_the_echoing_woods",
  goodId: "NighttimeWhispersInTheEchoingWoods",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.nighttime_whispers_in_the_echoing_woods_2",
          description: "set_descr.nighttime_whispers_in_the_echoing_woods_2",
          stats: { atk_percent: 18 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "set.nighttime_whispers_in_the_echoing_woods_4_1",
          serializeId: 37,
          title: "set_bonus.nighttime_whispers_in_the_echoing_woods_4",
          description: "set_descr.nighttime_whispers_in_the_echoing_woods_4_1",
          stats: { dmg_geo: 20 },
        },
        {
          type: "boolean",
          name: "set.nighttime_whispers_in_the_echoing_woods_4_2",
          serializeId: 38,
          title: "set_bonus.nighttime_whispers_in_the_echoing_woods_4",
          description: "set_descr.nighttime_whispers_in_the_echoing_woods_4_2",
          stats: { dmg_geo: 30 },
          condition: {
            type: "boolean",
            name: "set.nighttime_whispers_in_the_echoing_woods_4_1",
          },
        },
      ],
    },
  },
};
