// GENERATED by gen-armory.mjs — do not edit
/**
 * PrayersForIllumination — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "PrayersForIllumination". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/PrayersForIllumination.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const prayersForIllumination: DbObjectArtifactSet = {
  name: "artifact_set.prayers_for_illumination",
  goodId: "PrayersForIllumination",
  bonus: {
  },
};
