// GENERATED by gen-armory.mjs — do not edit
/**
 * PrayersForWisdom — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "PrayersForWisdom". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/PrayersForWisdom.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const prayersForWisdom: DbObjectArtifactSet = {
  name: "artifact_set.prayers_for_wisdom",
  goodId: "PrayersForWisdom",
  bonus: {
  },
};
