// GENERATED by gen-armory.mjs — do not edit
/**
 * PrayersForSpringtime — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "PrayersToSpringtime". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/PrayersForSpringtime.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const prayersToSpringtime: DbObjectArtifactSet = {
  name: "artifact_set.prayers_to_springtime",
  goodId: "PrayersForSpringtime",
  bonus: {
  },
};
