// GENERATED by gen-armory.mjs — do not edit
/**
 * ResolutionofSojourner — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "ResolutionOfSojourner". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/ResolutionofSojourner.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const resolutionOfSojourner: DbObjectArtifactSet = {
  name: "artifact_set.resolution_of_sojourner",
  goodId: "ResolutionofSojourner",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.resolution_of_sojourner_2",
          description: "set_descr.resolution_of_sojourner_2",
          stats: { atk_percent: 18 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.resolution_of_sojourner_4",
          description: "set_descr.resolution_of_sojourner_4",
          stats: { crit_rate_charged: 30 },
        },
      ],
    },
  },
};
