// GENERATED by gen-armory.mjs — do not edit
/**
 * RetracingBolide — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "RetracingBolide". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/RetracingBolide.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const retracingBolide: DbObjectArtifactSet = {
  name: "artifact_set.retracing_bolide",
  goodId: "RetracingBolide",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.retracing_bolide_2",
          description: "set_descr.retracing_bolide_2",
          stats: { shield: 35 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "common.char_status_shield",
          serializeId: 13,
          title: "set_bonus.retracing_bolide_4",
          description: "set_descr.retracing_bolide_4",
          stats: { dmg_normal: 40, dmg_charged: 40 },
        },
      ],
    },
  },
};
