// GENERATED by gen-armory.mjs — do not edit
/**
 * Exile — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "TheExile". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/Exile.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const theExile: DbObjectArtifactSet = {
  name: "artifact_set.the_exile",
  goodId: "Exile",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.the_exile_2",
          description: "set_descr.the_exile_2",
          stats: { recharge: 20 },
        },
      ],
    },
  },
};
