// GENERATED by gen-armory.mjs — do not edit
/**
 * TinyMiracle — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "TinyMiracle". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/TinyMiracle.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const tinyMiracle: DbObjectArtifactSet = {
  name: "artifact_set.tiny_miracle",
  goodId: "TinyMiracle",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.tiny_miracle_2",
          description: "set_descr.tiny_miracle_2",
          stats: { res_pyro: 20, res_cryo: 20, res_hydro: 20, res_electro: 20, res_enemo: 20, res_geo: 20, res_dendro: 20 },
        },
      ],
    },
  },
};
