// GENERATED by gen-armory.mjs — do not edit
/**
 * TravelingDoctor — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "TravelingDoctor". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/TravelingDoctor.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const travelingDoctor: DbObjectArtifactSet = {
  name: "artifact_set.traveling_doctor",
  goodId: "TravelingDoctor",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.traveling_doctor_2",
          description: "set_descr.traveling_doctor_2",
          stats: { healing_recv: 20 },
        },
      ],
    },
  },
};
