// GENERATED by gen-armory.mjs — do not edit
/**
 * UnfinishedReverie — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "UnfinishedReverie". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/UnfinishedReverie.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const unfinishedReverie: DbObjectArtifactSet = {
  name: "artifact_set.unfinished_reverie",
  goodId: "UnfinishedReverie",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.unfinished_reverie_2",
          description: "set_descr.unfinished_reverie_2",
          stats: { atk_percent: 18 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "stacks",
          name: "set.unfinished_reverie_4",
          serializeId: 39,
          title: "set_bonus.unfinished_reverie_4",
          description: "set_descr.unfinished_reverie_4",
          maxStacks: 5,
          stats: { dmg_all: 10 },
        },
      ],
    },
  },
};
