// GENERATED by gen-armory.mjs — do not edit
/**
 * VermillionHereafter — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "VermillionHereafter". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/VermillionHereafter.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const vermillionHereafter: DbObjectArtifactSet = {
  name: "artifact_set.vermillion_hereafter",
  goodId: "VermillionHereafter",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.vermillion_hereafter_2",
          description: "set_descr.vermillion_hereafter_2",
          stats: { atk_percent: 18 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "boolean",
          name: "set.vermillion_hereafter_4_burst",
          serializeId: 23,
          title: "set_bonus.vermillion_hereafter_4",
          description: "set_descr.vermillion_hereafter_4_1",
          stats: { atk_percent: 8 },
        },
        {
          type: "stacks",
          name: "set.vermillion_hereafter_4_stacks",
          serializeId: 24,
          title: "set_bonus.vermillion_hereafter_4",
          description: "set_descr.vermillion_hereafter_4_2",
          maxStacks: 4,
          stats: { atk_percent: 10 },
          condition: {
            type: "boolean",
            name: "set.vermillion_hereafter_4_burst",
          },
        },
      ],
    },
  },
};
