// GENERATED by gen-armory.mjs — do not edit
/**
 * DewflowersGlow — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "VourukashasGlow". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/DewflowersGlow.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const vourukashasGlow: DbObjectArtifactSet = {
  name: "artifact_set.vourukashas_glow",
  goodId: "DewflowersGlow",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.vourukashas_glow_2",
          description: "set_descr.vourukashas_glow_2",
          stats: { hp_percent: 20 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.vourukashas_glow_4",
          description: "set_descr.vourukashas_glow_4_1",
          stats: { dmg_skill: 10, dmg_burst: 10 },
        },
        {
          type: "stacks",
          name: "set.vourukashas_glow_4",
          serializeId: 32,
          title: "set_bonus.vourukashas_glow_4",
          description: "set_descr.vourukashas_glow_4_2",
          maxStacks: 5,
          stats: { dmg_skill: 8, dmg_burst: 8 },
        },
      ],
    },
  },
};
