// GENERATED by gen-armory.mjs — do not edit
/**
 * WandererTroupe — artifact set port (faithful 1:1 from her raw ArtifactSet).
 *
 * goodId = the oracle registry key (the sets-*pc fixture / build-config lookup key);
 * her raw goodId is "WanderersTroupe". Conditions serialized from the live bonus tiers;
 * no-stat marker conditions and display-only (text_*) keys are dropped (numeric no-ops).
 * Source: raw/genshin_calc_pub/src/js/db/Artifacts/Set/WandererTroupe.js
 */

import type { DbObjectArtifactSet } from "@genshin/types";

export const wanderersTroupe: DbObjectArtifactSet = {
  name: "artifact_set.wanderers_troupe",
  goodId: "WandererTroupe",
  bonus: {
    2: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.wanderers_troupe_2",
          description: "set_descr.wanderers_troupe_2",
          stats: { mastery: 80 },
        },
      ],
    },
    4: {
      conditions: [
        {
          type: "static",
          title: "set_bonus.wanderers_troupe_4",
          description: "set_descr.wanderers_troupe_4",
          stats: { dmg_charged: 35 },
        },
      ],
    },
  },
};
